### ISSUE TITLE
watirwebdriver.com: update mobile page

### ISSUE THREAD

**Issue by jarib** [watir/watir#278]
This is a bit outdated: http://watirwebdriver.com/mobile-devices/

Someone who has done more mobile testing than I should fix that page to at least mention that watir-webdriver will work with selendroid, appium and ios-driver etc.

**Comment by titusfortner** [comment]
@bret @brentlavelle is this something you guys can help with? :)

**Comment by p0deje** [comment]
I'd say we need to brand new watir.com which includes info from watirwebdriver.com as well.

**Comment by brentlavelle** [comment]
This isn't my area.  I was using Appium to test native mobile apps but have since moved on to Calabash.  So, I'm not driving browsers but native apps.

**Comment by bret** [comment]
+1 to Alex's suggestion.

My experience with mobile testing has either been testing native apps (as
Brent mentions) or else by testing browsers on a computer but resizing it
to mobile size in order to simulate the mobile experience using responsive
pages. I would think this would be the best approach for most mobile
testing.

**Comment by titusfortner** [comment]
moving issue to watir website repo
