### ISSUE TITLE
Extend .fire_event to allow for additional parameters needed for new html5 events

### ISSUE THREAD

**Issue by Chuckv** [watir/watir#316]
I propose that in order to better support level3 events such as wheel and mouse events, that we enhance the fire_event method to accept an optional hash in addition to the event name.  The hash could contain needed parameter name, value pairs that need to be populated for the proper firing of events like onwheel

Background / additional info:

New 'level3'  events relating to mouse wheel scrolling (http://www.w3.org/TR/DOM-Level-3-Events/#events-wheelevents) need 'delta' parameters provided to indicate the direction and amount of movement of the mouse wheel.  Without being able to provide this parameter, firing a 'wheel' event has basically zero effect as the JS code receiving the event needs the parameter to make sense of the event.  The 'standard' event is now defined as 'wheel' (onwheel) and is documented pretty well by mozilla here https://developer.mozilla.org/en-US/docs/Web/Events/wheel.  As you can see it allows for multiple parameters to indicate the scrolling movement of the wheel (x,y,z,unit)

The Wheel event replaces some older events (different in different browsers) documented reasonably well at http://www.javascriptkit.com/javatutors/onmousewheel.shtml (which has a nice little inline demo) While only having one or two parameters, even these older deprecated events basically don't work without being able to provide the 'delta', and folks testing for browser compatibility with older browsers may still need to be able to fire these events and include parameters when doing so. 

In addition to wheel events where we need to indicate direction+distance along at least one axis, there are also level3 mouse events which have parameters for things like alt, ctrl, shift keys being held down, which button(s) are pressed, etc.  Being able to include those parameters allows us to easily accommodate creating mouse events such as a drag and drop with a key like ctrl or alt held down, or something strange like a shift-left-mousedown.

One reason users need to be able to fire such events are Custom scrollbox controlls like the jQuery "slimScroll" control (see  http://rocha.la/jQuery-slimScroll for live examples you can try to script against) These controls are mainly manipulated by wheel events, or drag and drop of a div that is rendered as a scrollbar.  In some cases accessing the scrollbar div is very difficult (if autohide is enabled) and it would be far simpler to be able to just fire mousewheel events instead dragging the dammed bar.  However this is not currently possible because fire_event does not allow for any additional parameters to indicate the 'delta' value(s).

**Comment by Chuckv** [comment]
I know some of this would be 'easier' by creating some kind of method specifically to simulate scrolling the mouse wheel etc, but even so, there is always going to be a need to be able to fire specific events with specific parameters, so even if we made special mouse_scroll methods, I think we still ought to make this change to fire_event

**Comment by p0deje** [comment]
I'm personally against this due to the following reasons:

1. The event should happen upon user interaction, not explicit `#fire_event` call.
2. If event can only be triggered using `#fire_event`, then the test is not correct (i.e. does not work through user interaction) or this is something that should be handled by `AdvancedUserInteractions` in selenium-webdriver.

That's pretty much the same reason why selenium-webdriver lacks `#fire_event` method.

@titusfortner @zeljkofilipin Your thoughts?

**Comment by zeljkofilipin** [comment]
I do not really have an opinion about this, sorry. :)

**Comment by Chuckv** [comment]
Perhaps I am confused, how using watir-webdriver do we simulate the 'interaction' of a user moving their mouse over a given element and scrolling the mouse wheel down three ticks? (Causing a wheel event to be fired).  What does the code for that look like?  Go to the site I linked that has the inline example where scrolling the mouse wheel when over the image causes the images to change.  Show me how you code a test that validates scrolling the wheel causes the image to change.

**Comment by Blackbaud-TitusFortner** [comment]
I completely agree that encouraging the use of javascript to do things that a user can't do (force something to be visible, or take an action on a non-visible element) is a bad thing.

That being said, using a scroll wheel *is a frequently used user interaction, and one that Selenium doesn't directly support. The w3c spec for webdriver doesn't mention mouse wheel specifically, but has several descriptions of correct scrolling behvaior.

So, while I'm not opposed to the idea of fire event support for this, I'm not sure I understand why the current scrolling implementations are inadequate.
@Chuckv do you have an example for where this is necessary as opposed to the webdriver call for - element.wd.location_once_scrolled_into_view
What I see on the site you linked responds to the above command just fine.

**Comment by Chuckv** [comment]
So titus, on the page at http://www.javascriptkit.com/javatutors/onmousewheel.shtml you were able to cause the slideshow to change between showing the different seasonal images?  Can you share the code?  What about scrolling the scroll boxes at http://rocha.la/jQuery-slimScroll to change which paragraphs of text are in view?

**Comment by titusfortner** [comment]
I've already said there isn't a way to handle mouse wheel actions. I also don't think the example site that demos the availability of a function is a sufficient use case to warrant supporting non-webdriver interactions.

The real issue is whether you can scroll, and yes, the line of code I wrote in my last message will move the paragraphs into view so you can get the text from them.

first_p = browser.div(id: 'slimtest1').p
last_p =  browser.div(id: 'slimtest1).ps.last

first_p.text  => 'ipso lorem mumbo jumbo, etc...'
last_p.text => ''
last_p.wd.location_once_scrolled_into_view
first_p.text => ''
last_p.text => 'ipso lorem mumbo jumbo, etc...'

**Comment by titusfortner** [comment]
So, there is a mouse.atom that includes wheel interactions - https://github.com/SeleniumHQ/selenium/blob/master/javascript/atoms/mouse.js

I'm not certain how to build it or this is one that gets built, or the interface we'd need to provide to use it. @p0deje do you know how we would do this? Otherwise we can ping Simon or Jim about it.

**Comment by p0deje** [comment]
I have no idea how to call atoms from within Watir. I'm not even sure they will be available in all the drivers.

**Comment by titusfortner** [comment]
I'm going to consider this addressed once we implement #829
