### ISSUE TITLE
Direct Children

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#329]
@alexhanh recently suggested that [this behavior](http://www.natontesting.com/2009/08/19/how-to-get-only-direct-child-objects-in-watir/) makes more sense for a testing framework.

Currently it can be achieved by doing: 
browser.ul(:id, 'main').lis(xpath: './*')

Does it make more sense for a testing framework to make this the default behavior?

Also, one of the strengths of Watir is the lack of need to use xpath or css to access elements. As such, is there a more user-friendly / obvious way we can let users toggle between these two behaviors?

Watir.all_descendants = true
Watir.only_children = true
browser.ul(:id, 'main').lis.children
browser.ul(:id, 'main').lis.descendants
browser.ul(:id, 'main').lis(children: true)
browser.ul(:id, 'main').lis(descendants: true)
browser.ul(:id, 'main').child_lis
browser.ul(:id, 'main').descendant_lis

**Comment by p0deje** [comment]
My vote is :-1: for that because if we follow the children approach, the XPath is smth like `//ul[@id="main"/lis`, while currently it's `//ul[@id="main"//lis`. This means that if you want to skip few children, you can easily do it now, but if we change the approach, you will have to explicitly specify each children. This makes Watir API calls chain similar to writing XPath manually and makes tests brittle.

**Comment by alexhanh** [comment]
I also don't know if the behaviour should be default. In some cases, it seems direct children is what people expect it to be, in other cases not. Also according to @p0deje it seems like the current way allows more flexiblity.

In my personal experiences, most of the times when I'm quering for 'lis', 'trs' and 'tds', I expect and need only children. But a crawler, for example, could very well want to query for all the 'as' as descendants.

But what I'm pretty sure to suggest is to have a lean Watir way to query just direct children without having to use XPath or CSS selectors. In my experience of using Watir, the need to query direct children comes often enough to justify a shortcut. Hopefully we'll get more opinions about this. So how the syntax could look like?

`lis.children` does this get all the `lis` and return all of their children (regardless of the tag type)? Seems maybe too ambiguous. Same argument applies to `lis.descendants`.

`lis(children: true)` better since the additional children restriction ties to the `lis` more clearly.

`child_lis` the most tidy and explicit one, I think. I guess the bracket style allows more parameters to be added in the future (can't come up with ideas what right now). But I guess you could do the same with `child_lis(something: false)` too.

PS. I've personally used watir-webdriver far more for automation purposes than testing.

**Comment by p0deje** [comment]
Also, a good comment from Jari explaining why siblings should not be added to Watir - https://github.com/watir/watir-webdriver/pull/270#issuecomment-55246884.

It explains why I'm against the proposed changes.

**Comment by p0deje** [comment]
@titusfortner So, what's up with this?

**Comment by titusfortner** [comment]
@p0deje - Your code [here](https://github.com/watir/watir/issues/329#issuecomment-88753320) is the same? What is an example of how to use xpath to get only direct children our current code?

**Comment by p0deje** [comment]
Isn't your example still valid?

``` ruby
browser.ul(:id, 'main').elements(xpath: './*')
```

**Comment by titusfortner** [comment]
This was implemented with #451
