### ISSUE TITLE
Watir should provide a standard interface to HTML elements

### ISSUE THREAD

**Issue by abaird** [watir/watir#405]
We need two standard methods that:
- interacts with the element
- gets the element's representation

For example, let's say there is an interaction method "set". Calling `set` would have the following effects:

```
link.set - clicks on the link
checkbox.set - checks the checkbox
radio.set(true) - clicks the radio button
```

Let's say that there is a method "value" that gets the element's representation. Calling `value` would have the following effects:

```
link.value - returns the html
checkbox.value - returns whether or not the checkbox is checked
radio.value - returns whether or not the radio is selected
```

A code example can be found [here](https://github.com/bret/watircraft/blob/master/lib/extensions/watir.rb). The point of this is to provide frameworks a single method to interact with an element instead of having to alias all of Watir's different methods for interacting with elements.

This suggestion was raised during an Austin Homebrew Testers meeting.

**Comment by p0deje** [comment]
This seems strange to me. Why would `A#set` be aliased to `A#click`? The naming is strange here. Why would `A#value` return HTML and not `href` attribute?

More general question is why would you want to unify all the element methods?

**Comment by bret** [comment]
@titusfortner showed us some code that looked something like this (https://github.com/bret/watircraft/blob/master/lib/extensions/watir.rb) (Titus can you post your actual code?) and I said that I thought it was wrong that you had to write wrappers like this for watir. Instead Watir should provide a consistent methods that allowed you to set or get the value of an element.

Suggestion to use "value" doesn't actually work out because their is a collision with existing usage.

I agree that link.set is silly.

This proposal needs to be worked out in more detail.

**Comment by abaird** [comment]
Clearly I chose bad names for these methods. I have re-worded the original post. The names are still unwieldy, but hopefully less confusing now. Also, I meant href and not html.

This is just a _possible_ implementation. The root of the conversation though was the discussion around why [this code in Titus's watir_drops framework](https://github.com/titusfortner/watir_drops/blob/master/lib/watir_drops/page_object.rb#L45-L64) was something we felt like was code that Watir needed to handle and not have it be re-implemented in every page object framework.

**Comment by titusfortner** [comment]
[This is the code](https://gist.github.com/titusfortner/ad873ff38bfda98f52f3ea6acb618601) I was showing earlier this year. Instead of having to do a conditional to interact with a default action, we create them in the applicable classes.

I don't necessarily think we need to do this for *all elements, just the ones that make sense to use with a variable setter.

**Comment by p0deje** [comment]
I think it makes sense to unify interface for specific elements, so it'd be great to figure out that API before implementing it.

**Comment by titusfortner** [comment]
I'm still not sure this doesn't better belong in a page-object implementation. Another complication with this is whether to implement `Select` to default to text or value.

**Comment by azohra** [comment]
@titusfortner what about having select attempt both strategies? 

The primary reason I want to see this merged into Watir is so I can have Rubocop and Titus be happy. 

When I implement this into my PO with a giant case, Rubocop gun be mad 
When I implement this as a monkey patch, Titus gun be mad

I don't want anyone to be mad. 

p.s if we did this, we could effectively cut out 10-20 lines of code from every watir PO framework on the market and harmonize how folks are utilizing POs! Opinionated about ALL the things

**Comment by titusfortner** [comment]
@tk8817 

Bad: Monkey Patch
Good: PR & Discuss

**Comment by p0deje** [comment]
> When I implement this into my PO with a giant case, Rubocop gun be mad

This is easy, just refactor your code.

> When I implement this as a monkey patch, Titus gun be mad

Even easier, just avoid him.

**Comment by p0deje** [comment]
It would make sense if somebody can work out the API and propose it here to have some meaningful discussion. Without it, I don't think we're getting anywhere, so let's have something specific to discuss.

Or we can just leave that for wrappers like page-objects. IMO Watir **interface** should be concise and restrictive to inputs while **DSL** around it can be more declarative.

**Comment by titusfortner** [comment]
So, interestingly, a conversation with @jkotests in Toronto made me realize that this is what `#set` was originally designed to do.

This is what WatirDrops is doing to implement this now; I should double check it against Cheezy's gem:

```ruby
          case watir_element
          when Watir::Radio
            watir_element.set if val
          when Watir::CheckBox
            val ? watir_element.set : watir_element.clear
          when Watir::Select
            watir_element.select val
          when Watir::Button
            watir_element.click
          when Watir::TextField, Watir::TextArea
            watir_element.set val if val
          else
            watir_element.click if val
          end
```

The ideal is to have this in one line:
```ruby
watir_element.set val if val
```

This means aliasing `#set` to various methods in the various classes, with the superclass doing a `#click`.
1. `Radio` needs to accept and ignore a value parameter
2. `RadioSet`: alias `#select`
3. `Checkbox`: No Change, proposed behavior will work with existing code
4. `Select`: alias `#select` (requires #846)
5. `Button`: No Change, same behavior as `Element`
6. `TextField` & `TextArea`: No Change, proposed behavior will work with existing code
7. `Element`: `#set` can not be aliased, it needs to be added to `#method_missing` in case `content_editable?`

We should also implement a corresponding `#get` across all of the element types. I'm not sure we know what this means for everything right now (value? text? label?) Need to go through that code one at a time.

**Comment by titusfortner** [comment]
Because `#get` is a little ambiguous as far as whether it should return the value or the label / text, whichever route we take might not satisfy the end user's need. Since the primary use of this feature is for Page Object implementations, it is telling that there are no examples of this right now in any PO implementation we are aware of. Either Watir makes the decision everyone has to abide by, or it makes it configurable for the PO implementation to override. Either way, it seems like an unnecessary feature at this time. If a Page Object wants to implement this functionality, it's very straightforward.

```ruby
      subtype = element.to_subtype
      case subtype
      when Checkbox, Radio
        subtype.set?
      when Select # this is optional if you want it to return label value instead of attribute value
        subtype.value
      else
        subtype.text
      end
```
