### ISSUE TITLE
Calling Input#set

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#441]
The set method works on text_field
`browser.text_field(id: 'foo').set 'bar'`

but not input:
`browser.input(id: 'foo').set 'bar'`

It throws:
`ArgumentError: expected Hash or (:how, 'what'), got ["new value"]`

Because it is looking for a `Set` Element
I don't think this should error...

I have ideas for how to address, but for now this is just logging the issue for future discussion.

**Comment by samnissen** [comment]
This also fails on `.element`/`.elements`, even if the element is a `.text_field`.

``` ruby
> w = Watir::Browser.new
 => #<Watir::Browser:0x52ab566944c61332 url="about:blank" title="">
> w.goto "http://google.com"
 => "http://google.com"
> w.element({:id => 'lst-ib'}).present?
 => true
> w.element({:id => 'lst-ib'}).set("Hello")
ArgumentError: expected Hash or (:how, 'what'), got ["Hello"]
    from /path/to/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.1/lib/watir-webdriver/container.rb:47:in `extract_selector'
    from /path/to/.rvm/gems/ruby-2.3.1/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/svg_elements.rb:699:in `set'
    from (irb):6
    from /path/to/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

@titusfortner If I can help with the fix, let me know.

**Comment by p0deje** [comment]
We constantly have such collisions and for now deliberately exclude such elements from being generated.

**Comment by p0deje** [comment]
For example:

https://github.com/watir/watir/blob/b4c0105e85572b4bbc7e47f04ebbaad7a0712dbc/lib/watir/generator/html/generator.rb#L7-L10
https://github.com/watir/watir/blob/b4c0105e85572b4bbc7e47f04ebbaad7a0712dbc/lib/watir/generator/svg/generator.rb#L12-L14

**Comment by samnissen** [comment]
@p0deje I'm a real novice on this codebase but it looks like me like maybe `.set` is conceptually overloaded. 

Here are all of the places `.set` is defined, I think:
1. https://github.com/watir/watir/blob/99b5d467de5022d6985a6a494b408fa561da0f2c/lib/watir/elements/file_field.rb#L11-L14
2. https://github.com/watir/watir/blob/99b5d467de5022d6985a6a494b408fa561da0f2c/lib/watir/alert.rb#L66-L69
3. https://github.com/watir/watir/blob/99b5d467de5022d6985a6a494b408fa561da0f2c/lib/watir/elements/checkbox.rb#L18-L20 -- which should probably move in tandem with `.set?` https://github.com/watir/watir/blob/99b5d467de5022d6985a6a494b408fa561da0f2c/lib/watir/elements/checkbox.rb#L27-L30
4. https://github.com/watir/watir/blob/99b5d467de5022d6985a6a494b408fa561da0f2c/lib/watir/elements/radio.rb#L8-L10 -- which should probably move in tandem with `.set?` https://github.com/watir/watir/blob/99b5d467de5022d6985a6a494b408fa561da0f2c/lib/watir/elements/radio.rb#L18-L21
5. https://github.com/watir/watir/blob/99b5d467de5022d6985a6a494b408fa561da0f2c/lib/watir/user_editable.rb#L10-L14
6. https://github.com/watir/watir/blob/99b5d467de5022d6985a6a494b408fa561da0f2c/lib/watir/elements/svg_elements.rb#L578-L580

I'd be a fan of renaming them to more localized concepts, like `set` -> `input` for `UserEditable` or `set` -> `check` for `Checkbox`. `SVGElements#set` should probably remain unchanged since it matches the rest of the naming of the `Container` module. 

Would this fix these issues? Maybe you've already considered and rejected this idea. Maybe this is obvious, but if this change is to be made, we should start asap, to give some deprecation notice.

**Comment by p0deje** [comment]
The issue happens only on elements which don't implement custom `#set` method, so that instead it calls `SVGElements#set`.

Possible solutions are:
1. Remove `SVGElements#set` completely, so that it will raise `NoMethodError`.
2. Rename existing methods like @samnissen proposes.

I don't know which one is better, but the first is definitely easier :)

**Comment by samnissen** [comment]
Rather than delete it might be preferable to rename `SVGElement.set` to `SVGElement.xset` (or similar), with a sprinkling of documentation to that effect...

**Comment by p0deje** [comment]
The method names are automatically generated from SVG specification, so I don't see how renaming should be done. Also, it would be surprising if other method names match tag name, but this one don't.

**Comment by titusfortner** [comment]
`#set` is no longer getting generated in `svg_elements.rb` so this no longer matters.
