### ISSUE TITLE
What are known reasons to use watir not capybara?

### ISSUE THREAD

**Issue by Nakilon** [watir/watir#444]

**Comment by titusfortner** [comment]
This is a question, not an issue, but it is a good question, and I'd like to see us come up with a more thorough answer for our website.

In general, I prefer Watir's object oriented library approach to capybara's DSL framework. It has more features and is more flexible. That being said, it doesn't integrate as well into rails test suites. At this point I'd recommend using capybara if running it as part of a rails test suite, and Watir if it is part of a black box testing suite against a deployed server. 

There is a Watir rails gem, but I've never used it and it seems to be tailored to people who are already familiar with Watir (at least based on the readme). @jarmo or @p0deje can either off you extol the virtues of that gem as an alternative to capybara in a rails test suite?

**Comment by jarmo** [comment]
@titusfortner can you explain how capybara integrates into Rails test suite? I have not used it that's why I'm asking :)

Being the original author of [watir-rails](https://github.com/watir/watir-rails) I don't see anything missing from it to test Rails applications.

**Comment by titusfortner** [comment]
I've only run what other people have written with Capybara. (I really need to actually write my own Rails app). 

In that codebase, Rails spun up a server on some random port based on the code in the repo, and the Capybara code ran its against it. It made heavy use of FactoryGirl to pull data from the internals of the application to populate the database, making it more grey box than black box. Based on that experience, I'm not sure how I'd get Watir to do the same thing... But that's my only experience with it. :)

**Comment by jarmo** [comment]
With watir-rails you can do exactly the same thing as you just described above.

**Comment by titusfortner** [comment]
Excellent! @Rodney-QAGeek let's add this to our list for putting something more comprehensive together about using it, maybe some kind of compare/contrast of the features. Then we can proselytize Watir for the discerning Ruby developer. :-D

**Comment by Nakilon** [comment]
1. Yes, it is a question, not an issue. If I ask it on SO, it would be deleted as "answers to this question will tend to be almost entirely based on opinions, rather than facts, references, or specific expertise.", so I thought instead I should do it here.
2. I use Capybara for _a black box testing suite against a deployed server_ with RSpec.
   At https://watir.com/examples/ I don't see the difference from Capybara except of few more predefined selectors, but they can be easily defined with [custom selectors](https://github.com/jnicklas/capybara#xpath-css-and-selectors) -- when you write a dozen of tests around a one page you'll make some kinds of "custom selectors" shortcuts anyway.

**Comment by RodneyU215** [comment]
Cool, will do Titus!

Victor, I believe this is a completely valid question to raise. I have used both Watir and Capybara for big selenium projects. It's been a while since I've looked at any recent changes to Capybara, but at the time when I first made the decision to switch I thought this [blog](https://watirmelon.com/2011/12/03/a-tale-of-three-ruby-automated-testing-apis-redux/) was very helpful.

**Comment by titusfortner** [comment]
@Nakilon - I agree this is a better place to ask your question than SO. We could probably also be having this conversation on the Watir Google Group, but it is easier to share code here. I just felt the need to note that I was handling this issue differently than other questions that are posted as issues here. :)

I still want to write up something more comprehensive because I don't exactly love a lot of points in Alister's post. At one point I started to put together a comparison of ruby frameworks and libraries like [Capybara](https://github.com/titusfortner/rb_test_frameworks/blob/master/spec/capybara_spec.rb) and [Watir](https://github.com/titusfortner/rb_test_frameworks/blob/master/spec/watir_spec.rb), but I didn't get very far. I'd love to see more sharing and comparisons of code between users of each.

Capybara has a few features that I think Watir should implement, but I suspect if/when we do a full feature comparison there will be a number of Watir features missing in Capybara. Overall I see two main (but related) differences. Let's use this code for example:

``` Ruby
Capybara.current_driver = :selenium

second_window = window_opened_by do
  click_button 'Open Window'
end

within_window second_window do 
  within_fieldset('Employee') do
    fill_in 'Email', with: 'user@example.com'
  end
end
```

vs

``` Ruby
browser = Watir::Browser.new

browser.button(text: 'Open Window').click
browser.window(title: 'Second Window").use

element = browser.fieldset(id: 'Employee').text_field(name: 'Email')
element.set 'user@example.com'
```
1. DSL vs Library. A DSL is more "magic." Many people like the magic when they get used to it, but it can also be limiting.
   - For common things like filling in a value on a field, Capybara is more succinct, but less object oriented. It takes actions without distinguishing what objects those actions are being taken on and what parameters each action is using.
   - Capybara has significantly more configuration settings than Watir to tweak what magic you want to use, which means the implementation is not always obvious looking at the test code. 
   - Capybara dumps a bunch of methods in the global name space, which is not ideal
   - Capybara source code is harder to follow because the objects being acted on are not clear, and the parameters being passed in can take a circuitous route to get to the object that they are needed for.
   - Capybara encourages closures since it discourages objects (see the 3 in the above example, vs none for Watir), which is arguably less clear.
2. Element Location & Usage (this is where Watir objectively shines against Capybara)
   - There is no need to register custom selectors
   - There is no need to use XPath with Watir
   - There are only a few instances where you need to use CSS with Watir
   - Every valid html element has its own object with automatically generated attributes as first class locators and methods
   - Watir Elements are better encapsulated; only supported actions can be performed and attributes accessed for any particular Watir element.
   - Watir requires being explicit about which selector instead of magically trying to figure it out, which is both more clear and results in fewer unnecessary driver calls.
   - Nested elements are easy to reference in Watir

Perhaps a 3rd reason is that the maintainers of the Selenium code are also the maintainers of the Watir code. :)

Like I said, I'd love to have more discussion within the community about when which tool is good for which things.

**Comment by Nakilon** [comment]
1. While you mentioned the 'magic', I actually don't use it in Capybara -- I just chain methods exactly like you did in Watir example. It's not disallowed. And in that way I also don't face the difficulty to explore the internal source code.  
2. I don't get you about XPath. The choice of locators heavily depends on the frontend framework. And I use XPath for examples like: a) `//button[text()='foo']` b) when I need to get the parent element that is not supported by current CSS W3C specification.
3. The thing I remember when choosing the library for website testing two years ago was that Capybara was "easily" switchable from one driver to another, between real browser and webkit, etc. -- I don't remember the full tree of possibilities though.

**Comment by titusfortner** [comment]
You just don't need XPath in Watir:
`browser.button(text: 'foo')`
`browser.button(text: 'foo').parent`

Watir is easily switchable between any of the available drivers, including phantomjs, which is headless, but which I recommend against using because headless is overrated. :)
`Watir::Browser.new :phantomjs`
`Watir::Browser.new :firefox`
`Watir::Browser.new :safari`

**Comment by Nakilon** [comment]
Seems like Capybara also can `text:` http://www.rubydoc.info/github/jnicklas/capybara/Capybara/Node/Finders

**Comment by titusfortner** [comment]
I was just copying your example without the XPath.

**Comment by Th33x1l3** [comment]
@titusfortner headless is not overrated. Testing in a real browser with headless can be a necessity. Think docker container test environment. I don't use phantomjs, because it's a 'fake browser'. I use chrome, firefox

**Comment by titusfortner** [comment]
@Th33x1l3 by headless I wasn't intending to refer to xvfb, but rather "fake" browsers like phantomjs and capybara-webkit. This conversation will blissfully be much less of an issue as soon as Google implements [runtime headless mode for Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=612904)

**Comment by Th33x1l3** [comment]
@titusfortner I'm waiting for that too, because docker has a issue with memory and Chrome/firefox. And having a lesser footprint browser and already headless, maybe that way it will help not running in that issue.

**Comment by p0deje** [comment]
I'm going to close this since it's not really an issue but a discussion that should go to watir-general Google group.

**Comment by Rajagopalan-M** [comment]
@titusfortner 

 "Perhaps a 3rd reason is that the maintainers of the Selenium code are also the maintainers of the Watir code. :)"

what do you mean by this? So you people are maintaining selenium ruby binding as well?

**Comment by titusfortner** [comment]
Yes, though the Capybara dev has been active & helpful in working with us over the past couple years, so that probably isn't the best reason to list.

**Comment by Rajagopalan-M** [comment]
@titusfortner 

So 
These logs are released by you people? These changes are done from people from WATIR Team?
```
3.11.0 (2018-03-11)
===================

Ruby:
  * No changes in Ruby bindings for this release

3.10.0 (2018-03-02)
===================

Ruby:
  * Added Errno::EAFNOSUPPORT to the list of ignored errors when finding port (thanks @jtarchie)
  * Added automatic conversion of noProxy to the list of strings as required
    by W3C WebDriver Specification (issue #5004)
```

**Comment by titusfortner** [comment]
It's pretty trivial up look at the git history of these things.
