### ISSUE TITLE
drag_and_drop_on not working

### ISSUE THREAD

**Issue by royroque** [watir/watir#544]
also posted at:
[http://stackoverflow.com/questions/43127027/watir-6-2-1-does-not-support-drag-and-drop-anymore](url)

Unable to perform drag and drop (we don't often use drag_and_drop_on so I don't remember the last time this method worked; but I know for a fact that it used to work with the previous watir-webdriver versions)

Current config:

- watir (6.2.1)
- selenium-webdriver (3.3.0)
- IE11 / Chrome56 / FF52

Example Code Below (with URL):

   ```
 irb(main):037:0> browser.url
    => "http://the-internet.herokuapp.com/drag_and_drop"
    irb(main):038:0> a.flash
    => #<Watir::Div: located: true; {:id=>"column-a", :tag_name=>"div"}>
    irb(main):039:0> b.flash
    => #<Watir::Div: located: true; {:id=>"column-b", :tag_name=>"div"}>
    irb(main):040:0> a.drag_and_drop_on b
    => nil
    irb(main):041:0> a.drag_and_drop_on b
    => nil
```

**Comment by titusfortner** [comment]
Interesting. The Watir spec correctly drags and drops an element, but I can duplicate this bug.
I can also duplicate the bug with Selenium directly, so this should get submitted on the issue tracker there instead of here.

But pretty much I can duplicate it with every driver & old versions of Selenium so I might just blame Dave's site. :)
