### ISSUE TITLE
IE web driver is not able to use window opened via active x control

### ISSUE THREAD

**Issue by nitimagulati** [watir/watir#553]
A pop up window opens up through Active x control, when page loads.
IE web driver is not able to use that window.
2 windows are there one parent and another which is opened as a pop up but browser.windows.size still shows 1.
Following is the link which opens up pop up window at page load.
https://www.priceline.com/stay/search/hotels/3000008602/20170905/20170907/1/?searchType=CITY

selenium-webdriver (3.4.0)
watir-webdriver (0.8.0)
webdriver-user-agent (7.3)

**Comment by titusfortner** [comment]
This would be a Selenium / IE Driver issue, not a Watir issue. Please [open this bug there](https://github.com/SeleniumHQ/selenium/issues/new). Make sure you specify which OS, version of IE & 32bit vs 64bit version of the driver. (you might try switching to the other bit version of the driver because different things in IE are controlled by each, unfortunately).
