### ISSUE TITLE
Watir expects element to come into view before it interacts with it

### ISSUE THREAD

**Issue by rails4sandeep** [watir/watir#576]
Not sure after which release, because I was using watir on and off every few months.

Lately, Watir expects for an element to come into view before we can interact with it.

For example if I have a form and submit button that is not currently in view, earlier I would be able to click it even if it is not visible. 
However now it does not seem to be possible. 

I need to scroll down using `@b.send_keys(:page_down)` so that i scroll down to the end of the file.

Having said that, irrespective of whether the element is visible on the screen or not, `@b.element(attribute, value).exists?` returns true.

So, we also need a way to find out if the page element is visible on the screen or not

**Comment by p0deje** [comment]
In order to click and element, it has to be:

a) visible
b) in the current viewport

If it's not visible, Watir throws an error. This can be checked by `Element#visible?` method. If it is visible but not in the viewport, Watir (actually underlying Selenium) will automatically scroll it into view. 

I don't fully understand the question really.

**Comment by titusfortner** [comment]
You could never click an element that is not visible. In previous versions, taking a click action on an element that does not exist or is not visible would have thrown an exception. As of Watir 6.0, instead of raising an exception, Watir will poll for the element to become interactable (some combination of displayed, enabled, not read-only, etc) and then raise the exception if it is not successful in the established time.

Watir's `#present?` and `#visible?` methods rely on Selenium's `displayed` endpoint. The algorithm for this value does not consider whether the element is in the viewport or not, only whether the element is explicitly hidden by property or otherwise obscured by another element in the DOM. 

What is the use case for determining "Visible on the Screen?" This sounds like a design requirement not a functional requirement. Perhaps something like Applitools would be a better solution? One might be able to do this by getting the element location and calculating the viewport, but that's not really in the scope of what Watir does.

On a separate note, if you want to manipulate the viewport, there is an excellent [watir-scroll](https://github.com/p0deje/watir-scroll) gem with that capability.
