### ISSUE TITLE
iframe to_subtype different from getting an iframe initially

### ISSUE THREAD

**Issue by akostadinov** [watir/watir#588]
When you get element and to `#to_subtype` it behaves differently compared to when element is selected with the proper subtype to begin with. See this pry log:

```
> br = Watir::Browser.new(:firefox)
=> #<Watir::Browser:0x6ff1d1b5fbe11e56 url="about:blank" title="">
> br.goto "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe"
=> "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe"
> el = br.element(:xpath=>"//iframe")
=> #<Watir::HTMLElement: located: false; {:xpath=>"//iframe"}>
> subtype = el.to_subtype
=> #<Watir::IFrame: located: true; {element: (selenium element)}>
> iframe = br.iframe(:xpath=>"//iframe")
=> #<Watir::IFrame: located: false; {:xpath=>"//iframe", :tag_name=>"iframe"}>
> iframe.element(:xpath=>"//iframe").exist?
=> false
> subtype.element(:xpath=>"//iframe").exist?
NoMethodError: undefined method `switch!' for nil:NilClass
from ~/.gem/ruby/gems/watir-6.4.3/lib/watir/elements/iframe.rb:25:in `switch_to!'
```

Looking at the source, I see `#locate` returns `nil` when `@selector` is empty. I think that `@selector` needs to be passed to the new object by `#to_subtype`.

I'm not sure whether this is the correct fix though. The way one gets an IFrame element shouldn't prevent operations over it. I mean whether I did `browser.element(...).to_subtype` or `browser.iframe(...)`, I should be able to use the resulting object in the same way. If there are other ways one can obtain the `iframe` element, it should work equally well. I don't know the watir code well enough to know if a more generic fix can be implemented.

**Comment by titusfortner** [comment]
`Element#to_subtype` initializes a `Watir::Element` instance with an instance of a `Selenium::WebDriver::Element`. 

Since the `IFrame` class was created in `watir-webdriver`, this has been in the `#assert_exists` method:
`raise UnknownFrameException, "wrapping a Selenium element as a Frame is not currently supported"`

The reason you're seeing the issue you reported and not the exception is because I've refactored some things that have prevented the exception from getting properly raised. So the short term fix is to get the exception back in there.

From there we have more problems... 

Frames are tricky elements because of how Watir handled automatically switching into and out of them for you. We have a slightly kludgy concept called a `FramedDriver` to help with it, in spite of a few unsuccessful attempts I've made at alternate implementations. Essentially, it is impossible to know if an iframe element has gone stale, or if the driver is just in the wrong browsing context level to see it, so Watir conservatively assumes it is stale and relocates it. This is why the error above was there, since you can't relocate a `Watir::Element` without a unique selector. There is probably a way to refactor the code to better handle this, but it wouldn't be trivial.

Another option is for us to change `#to_subtype` from
`klass.new(@query_scope, element: wd)`
to
`klass.new(@query_scope, @selector.merge(element: @element))`

Which means that if there is a unique selector it will get it and be able to relocate with it. I think this would work... but then it raises the question of why you are calling `#to_subtype` on an element for which you already have a unique selector available. What makes sense about using `br.element(:xpath=>"//iframe"). element(:xpath=>"//iframe") ` instead of `br.iframe.iframe`? Maybe if I better understand the use case I'll know if the solution.

**Comment by akostadinov** [comment]
We have written a system to interact with elements based on YAML rules. It's useful for readability of the tests (on the other hand is often limiting especially when you want loops). The idea behind `#to_subtype` is to not bother the user to specify an element type. Also at least in the past not all subtypes supported all selector types.
We figured that we can nest some rules for more reliable selectors not only when frames are present but also with regular elements. Rule to check several elements under a frame and rule to check several elements inside some other container in the web page can use the same syntax.
It is just that - trying to reduce clutter for our use case.

To me it makes sense to keep element selector after `#to_subtype` - making the element as much as possible compatible with the source element. Otherwise what would be the use case of `#to_subtype`?

btw the idea was to make the yaml system accessible to community, just not sure yet whether it really makes as much sense as initially though. There is an [old version](https://github.com/openshift-qe/web4cuke) of it, but you can check it for illustrative purposes only. The new one is completely rewritten to allow completely custom interaction patterns while the old one more or less constraints you heavily. I'll upload the code some day anyway when I have a little time.

**Comment by titusfortner** [comment]
> Also at least in the past not all subtypes supported all selector types.
Which ones do you mean?

Primary use cases:
1. Convert ElementCollection of mixed element types
2. Input classes
3. Javascript located elements
4. `#parent` also used to use it, but we changed it from JS to XPath implementation

Though, now I'm wondering if it wouldn't make sense for all values located by generic element method to automatically subclass... I can write some code and see what it looks like.

As for Spreadsheet & Yaml & keyword based Page Object alternatives, I'm not a fan of the lack of flexibility and encapsulation, even though I know people who swear it is the only way they can get their manual testers to do it. :-/ I'd much prefer teaching people to use a good Page Object abstraction.

**Comment by akostadinov** [comment]
Automatic `#to_subtype` sounds interesting. wrt your last paragraph - that's what I can't definitively decide yet.

**Comment by titusfortner** [comment]
Ok, right, so, you can't auto-subtype and still be lazy loading. :) Scratch that idea.

**Comment by titusfortner** [comment]
fixed #591

**Comment by akostadinov** [comment]
Hi again. Thanks a lot for the quick turnaround!
I have tested these changes and they are working for our use case. Do you know when there will be a new watir rc build?

With the changes, the object produced by `subtype` is `#<Watir::IFrame: located: true; {:xpath=>"//iframe"}>`.
The object produced by `browser.iframe` is `#<Watir::IFrame: located: false; {:xpath=>"//iframe", :tag_name=>"iframe"}>`.
So far I don't see any side effects of `tag_name` missing from `subtype` but I thought to mention this for you to decide whether it is a problem or not. `subtype.tag_name` returns the correct value for me, probably things are ok.

**Comment by titusfortner** [comment]
If we added the tag name to the selector it could end up relocating the wrong element.

Consider that we do:
`browser.element(index: 4).to_subtype`

if that is a div, and we added it to the locator:
`browser.element(tag_name: 'div', index: 4)`

This would return a different Div

**Comment by akostadinov** [comment]
Thank you for looking into this, makes sense.
