### ISSUE TITLE
Remove Deprecated Features

### ISSUE THREAD

**Issue by titusfortner** [watir/watir#594]
* Remove support for old-style parameters where keywords have been implemented
* Remove `legacy_wait.rb`
* Remove all timing warnings
* Remove support for `Watir#prefer_css`
* Remove support for `Watir#always_locate`
* Remove support for `Watir#relaxed_locate` (dependent on #587)

**Comment by akostadinov** [comment]
Best option in my opinion is to remove `relaxed_locate` but allow individual operations to be forced on an object regardless it's visibility.

```
  my_hidden_field = browser.input(...)
  my_hidden_field.present.set "my value"
```

The `#present` method could return a clone of the element with `present?` returning always true. I guess other possible implementations could also work.

At the moment some fields have to be set using js due to js editors being present on the page. That IMO is an unnecessary complication. It's easier to just set the underlying text field. Using the js editor API doesn't validate UX anyway. So setting the field value easily is the better option in most use cases IMO.

Also other use cases may benefit from this, when for example one has hidden form fields controlled by some whatever sort of js.

**Comment by titusfortner** [comment]
#587 is going to open up a lot of options for users to configure things if they want something other than the default behavior, and should allow us to clean up a bunch of code.

@akostadinov are you in our #watir channel in Selenium Slack? (http://seleniumhq.herokuapp.com/)

**Comment by akostadinov** [comment]
I just requested an invite. Not there yet. Thanks for pointing this out!

**Comment by titusfortner** [comment]
merged for 7 beta
