### ISSUE TITLE
Capabilities should make setting downloads easier

### ISSUE THREAD

**Issue by kshahkshah** [watir/watir#644]
As discussed on Slack (thank you) we couldn't determine how to properly set the directory for download using chromedriver (and perhaps FF?)

@titusfortner

**Comment by kshahkshah** [comment]
https://sites.google.com/a/chromium.org/chromedriver/capabilities <-- maybe helpful, didn't help me

**Comment by kshahkshah** [comment]
watir.com/guides/downloads/ <-- this needs to get updated

**Comment by kshahkshah** [comment]
Also @titusfortner how does one check for the name of the file downloaded, it's not always clear from parsing a link (redirect/streaming file e.g.)

**Comment by kshahkshah** [comment]
and finally, and this is perhaps a separately ticket, how can you wait until a file is downloaded

**Comment by kshahkshah** [comment]
the issue is that headless chrome doesn't respect setting prefs, and they have unassigned the issue so don't count on this being supported any time soon: 

https://bugs.chromium.org/p/chromedriver/issues/detail?id=1925

**Comment by jkotests** [comment]
@whistlerbrk, did you end up getting the download directory set? I eventually got it working with:

~~~~~~~~ruby
prefs = {
  download: {
    prompt_for_download: false,
    default_directory: download_directory
  }
}
b = Watir::Browser.new :chrome, options: {prefs: prefs}
~~~~~~~~

@titusfortner, what were you envisioning doing for this issue? Watir-Classic's ability for downloading files in IE11 is lacking, so my team is currently working on creating a hybrid test that calls out to Watir(-Webdriver) to do the downloading. If you know what functionality we need, I can look into it since I'm working in the area and still need more pull requests for Hackotoberfest.

**Comment by titusfortner** [comment]
@jkotests I'm thinking about adding something like `:download_directory` similar to `:headless`
This would do the right thing in Chrome:
```ruby
b = Watir::Browser.new download_directory: '/path/to/directory'
```

Though, I think some of the capabilities have had their defaults changed in Chrome since this ticket.

**Comment by jkotests** [comment]
@titusfortner , do all the browsers use `:prompt_for_download` or is that just a Chrome thing? It'd be a bit silly if  `:download_directory` is first-level, but you still need to do the extra nesting for `:prompt_for_download`. Could make `:prompt_for_download` also first-level or make the default true (cause why would you be testing the browser prompt).

**Comment by titusfortner** [comment]
Yeah, that's why it isn't already done. The thought is to take a handful of things that might apply across browsers and are common requests and make them easier to set. Headless & STP both made sense to do top level based on the special bang methods in Selenium; these might make more sense to do inside the options key. It's a lower priority right now, but I'm open to ideas.

**Comment by titusfortner** [comment]
So probably what we need to do is to just build off of this and create a library of common/interesting things: https://github.com/SeleniumHQ/selenium/issues/9111
@jkotests you probably already have a long list of this kind of thing from Stack Overflow answers? :)

I need to resist the urge to add more complications in the meantime.
