### ISSUE TITLE
A watir performance is lower than the watir-webdriver.

### ISSUE THREAD

**Issue by reinaldorossetti** [watir/watir#663]
## Meta -
Watir Version: watir (6.8.4, 6.8.1)
Selenium Version: selenium-webdriver (3.5.1, 3.0.0)
Browser Version: 61.0.3163.100
Browser Driver Version:  2.32.498550 (9dec58e66c31bcc53a9ce3c7226f0c1c5810906a)
OS Version: Windows 7

## Expected Behavior -
It should have the same performance as the previous version "watir-webdriver"
## Actual Behavior -
It has a lower performance.

## Steps to reproduce -
# script
https://github.com/reinaldorossetti/tests_solution_ruby/blob/master/BenchmarkFramework_watir_capybara_selenium.rb
# Metrics
https://docs.google.com/spreadsheets/d/1zkelsVmpAg5tI0wqLV1vut7RJIyfiW5eWOmikOhT7NE/edit?usp=sharing

**Comment by jkotests** [comment]
Can you elaborate on how you collected the Watir-Webdriver metrics?

If the entire script is run at once, both the "Watir" and "Watir-Webdriver" metrics would be coming from Watir 6.8.4. While the Watir-Webdriver benchmark has `require "watir-webdriver"`, with Watir 6 installed, it just ends up calling `require "watir"` (plus the deprecation message).

**Comment by reinaldorossetti** [comment]
Ok, I understand, I'm remove this gem and I will try again.

**Comment by reinaldorossetti** [comment]
A strange thing is that the watir always loses Speed to capybara, but when I comment on the "driver.close" and "session.driver.browser.quit" the watir it is a little faster than capybara.

C:\GitSpread\Tests>ruby BenchmarkFramework_watir_capybara_selenium.rb
       user     system      total        real
capybara
 [9276:9028:1009/100315.993:ERROR:shader_disk_cache.cc(237)] Failed to create sh
ader cache entry: -2
  0.296000   0.312000   0.608000 (  7.124619)
watir
 [5668:5772:1009/100322.176:ERROR:shader_disk_cache.cc(237)] Failed to create sh
ader cache entry: -2
  0.094000   0.109000   0.203000 (  6.469742)

C:\GitSpread\Tests>ruby BenchmarkFramework_watir_capybara_selenium.rb
       user     system      total        real
capybara
 [6176:7140:1009/100715.793:ERROR:shader_disk_cache.cc(237)] Failed to create sh
ader cache entry: -2
  0.421000   0.171000   0.592000 (  6.615461)
watir
 [1060:2616:1009/100721.801:ERROR:shader_disk_cache.cc(237)] Failed to create sh
ader cache entry: -2
  0.093000   0.109000   0.202000 (  6.122965)

C:\GitSpread\Tests>ruby BenchmarkFramework_watir_capybara_selenium.rb
       user     system      total        real
capybara
 [12160:5776:1009/101925.486:ERROR:shader_disk_cache.cc(237)] Failed to create s
hader cache entry: -2
  0.218000   0.421000   0.639000 (  7.308014)
watir
   0.125000   0.094000   0.219000 (  6.219470)

**Comment by jkotests** [comment]
@reinaldorossetti, it would help if you could isolate specific problems. At the moment, it's hard to tell where you are having performance problems. Originally the issue seemed to be about Watir vs Watir-Webdriver, but now you are comparing Watir vs Capybara.

The benchmark script also includes everything from loading the gem to shutting down the browser. This makes it hard to tell where the performance degradation is, especially when it's only 1 second difference over many commands.

**Comment by reinaldorossetti** [comment]
My question regarding performance came over the post https://watirmelon.blog/tag/capybara/ this information is wrong, capybara have a better performance, but a little, this test is little, the test is very small, but thousands of tests the performance is a essential factor. I changed of watir-webdriver to watir, and I'm analysting the strong points in framework watir and one point is underperformance, but I need more tests.

**Comment by titusfortner** [comment]
That article doesn't really address performance per se, just different approaches to browser/test automation. I don't really agree with Alister on everything there, though to be fair I've pushed Watir in a slightly different direction from when he wrote that.

Watir & Capybara have similar goals, but approach them from completely different perspectives. Capybara is a Framework with a DSL, where Watir is a Library with an API. I'd be curious the speed differences, but I don't expect them to be that significant because we both take similar approaches to wrapping Selenium calls to provide better test automation functionality. Speed difference should not be your primary concern for choosing between them.

Either of them will be better than using straight Selenium, because they provide a lot of the wrapper and helper code that is essential to have well performing test suites.

I'm going to close this as an issue, because 6.4 just made a big performance update and I'm happy with where we're at right now. There's nothing immediately obvious to improve overall performance in the code right now. I'd still be interested in seeing your results, though.
