### ISSUE TITLE
WATIR API is not completely allowing to use Selenium Locators

### ISSUE THREAD

**Issue by Rajagopalan-M** [watir/watir#678]
To click a link WATIR API gives the following code,

`b.link(text: 'something').click`

but this is not utilizing Selenium 'link' locator, it is using 'xpath' locator of selenium at the back, the above code is getting converted in selenium

`driver.find_element(xpath: "//a[normalize-space()='something']").click`

So WATIR API is not giving any way to utilize the Selenium locator 'link', infact I can write the below code to invoke Selenium locator link

`b.element(link: 'something').click`

this will allow WATIR to write the following code in selenium

`driver.find_element(link: 'something').click`

but Titus Fortner feels that I am not using WATIR API in this place, Said that, WATIR can do following the arrangement,

`b.link(link: 'something').click`

but this code seems to be meaningless to me because 'b.link' is explicitely telling me that that is the link, So I am suggesting the following way 

we have two types of code to access link

```
b.link()
b.a()
```

but these two lines of code are doing the same Job, So we could use one of them for 'link' locator and another one for 'xpath'

when I write 

`b.link(text: 'something').click`

It needs to be converted into

`driver.find_element(link: 'something').click`

and when I write 

`b.a(text: 'something').click`

it needs to be converted into

`driver.find_element(xpath: "//a[normalize-space()='something']").click`

What's on your thoughts @jkotests ? @titusfortner ?

**Comment by jkotests** [comment]
@Rajagopalan-M, I disagree with supporting the `:link` locator for `#link` or `#a`. I actually disagree that `:link` should be supported in `#element`.

It's just not a locator that makes sense to me:
* Why is there a `:link` locator, but there isn't a similar `:button` locator?
* It also breaks the concept that passing in a `String` value does exact matches while a `Regexp` value does partial matching. Last I checked, using a `Regexp` will never return anything unless the element has a matching `link` attribute. Instead you have to use the `:partial_link_text` locator.

That said, I would be willing to support the underlying use case - ie matching based on the visible text. The support should be for all element types, not just links.

Note that we had talked about doing this in #631, but ended up deferring such work until a later time (ie someone requested the feature).

**Comment by titusfortner** [comment]
So the issue is that we've decided to have text locator find things that aren't displayed, where link text locator will only find displayed. We don't want to break backward compatibility. We could allow link_text or partial_link_text as locators for a link element in addition to a generic element, but that also gets weird with how regular expressions would work in this context.
The problem with matching visible text is that it would require iteration in most cases, and I'm not sure how we can implement it in a way that is different from just adding visible: true

**Comment by jkotests** [comment]
The difference with matching visible text and `visible: true` is when an element has visible and hidden text.

Consider the element:

~~~~~~~~html
<div>visible text <span style="display:none;">hidden text</div>
~~~~~~~~

Notice that you cannot locate the element on just the visible text:

~~~~~~~~ruby
browser.div(text: 'visible text').exists?                 #=> false
browser.div(text: 'visible text', visible: true).exists?  #=> false
~~~~~~~~

You have to locate the element using both the visible and hidden text:

~~~~~~~~ruby
browser.div(text: 'visible text hidden text').exists?     #=> true
~~~~~~~~

There are workarounds:

~~~~~~~~ruby
browser.divs.find { |div| div.text == 'visible text' }.exists?   #=> true 
browser.div(text: /visible text/).exists?                        #=> true
~~~~~~~~

I think there are places where this feature can be useful. However, I don't feel that the frequency of the problem is that high. At least, I cannot think of any recent Stack Overflow questions or places in my own code base.

**Comment by titusfortner** [comment]
@jkotests I get that there's a difference, but I don't know how we would implement a universal text-visible locator. This is one of the most convincing arguments for me to agree that the best option is to change the RegExp implementation of text locator instead of the String implementation.

The link text / partial link text would do it, but it would only apply to link elements, which as I said might not be worth doing since it doesn't really fit with the rest of the watir location system...

**Comment by jkotests** [comment]
@titusfortner, I must be misunderstanding something as I'm not following your comment. Doesn't your pull request #631 already implement a generic visible text and non-visible text locator?

**Comment by titusfortner** [comment]
@jkotests no, I implemented it the same as if you added `visible: true` to the selector, which has all of the problems you've raised.

**Comment by Rajagopalan-M** [comment]
@jkotests 

```
It's just not a locator that makes sense to me:
Why is there a :link locator, but there isn't a similar :button locator?
```

Oh so you don't like the way selenium is offering the locators? But what I am saying is, Since WATIR is the wrapper around selenium, it should be giving facility to utilize the whole power of selenium. WATIR should not be restricting in any way which selenium performs certain operation, Perhaps WATIR could improve the easiness but it can't eradicate any of it's way through which selenium does it's Job.

Ofcourse it allows us to access by calling `b.element()` but @titusfortner  feels that that goes outside the scope of WATIR API, If he says so, then he needs to provide the way to access selenium locator `link: `through some way. But WATIR API is closing the way to access `driver.find_element(link: 'something')` If it is so, then WATIR can't be the complete wrapper for selenium. That's my point.

**Comment by jkotests** [comment]
Sorry @Rajagopalan-M, I guess I just don't share the view that Watir has to provide everything or anything Selenium does. In my opinion, Watir's goal is to automate browsers using an intuitive syntax. The syntax should be same whether it's using Selenium, the old Watir-Classic WIN32OLE implementation, calling drivers directly or anything else underneath. The Watir API should be in no way dictated by the tools/libraries it uses. It should be dictated by its use cases. 

Again, I am agreeing that asking to locate elements by visible text is a reasonable request/use case. I just don't agree that it has to be a direct incorporation of `:link` and `:partial_link_text`.

**Comment by titusfortner** [comment]
Philosophically I agree with @jkotests 

Does #685 address both of your concerns?

**Comment by Rajagopalan-M** [comment]
@titusfortner May be @jkotests  right in one aspect but not completely, What's watir now? WATIR is allowing to write selenium ruby binding code in watir-classic syntax,  that's okay. But when you say  "WATIR is powered by Selenium", WATIR should allow user to access selenium coding to the fullest level possible. But it's not doing it if it doesn't pave the way to use link: locator. So I suggest to go with

> b.a(text: 'something').click

to 

> driver.find_element(xpath: "//a[normalize-space()='something']").click

and 

> b.link(text: 'something').click

to 

> driver.find_element(link: 'something').click

**Comment by titusfortner** [comment]
No, the locator absolutely needs the same behavior across the board. Watir is powered by Selenium to the extent that it uses Selenium to accomplish what it's API has always provided. It doesn't mean it has to conveniently wrap every feature in Selenium (which it doesn't). Watir provides access to the Selenium driver and element objects to handle anything that is outside Watir's API.

**Comment by Rajagopalan-M** [comment]
`" Watir provides access to the Selenium driver and element objects to handle anything that is outside Watir's API."`

Said that, don't be unhappy when I am asking someone to use

`b.element(link: 'soemthing').click`

**Comment by titusfortner** [comment]
I'm likely to remove that locator from being used directly by Watir regardless. If what Justin is working on looks good, then we can add that to our API instead.

**Comment by Rajagopalan-M** [comment]
@titusfortner which locator are planning to remove? I don't get you here.

**Comment by titusfortner** [comment]
I'm looking to deprecate `:link`, `:link_text` and `:partial_link_text` as locators since they don't fit in with the other Watir locators. They are the only locators that can't be combined with anything else, and they can't accept `RegExp` values. Now that we have `:visible_text` locator that can do those things, these others aren't necessary.

We'll do it in conjunction with the locators re-write I did in #689. We do still need to implement the performance improvements of using those Selenium locators directly when possible for `Anchor` class.

**Comment by titusfortner** [comment]
Ok, we've made the changes we intend to for this.
