### ISSUE TITLE
Github reports security vulnerability in active support dependency

### ISSUE THREAD

**Issue by bret** [watir/watir#696]
## Meta -
Watir Version: 
Selenium Version: 
Browser Version: 
Browser Driver Version: 
OS Version: 

  | watir/watir
-- | --
Known moderate severity security vulnerability detected in activesupport < 4.1.11 defined in watir.gemspec.watir.gemspec update suggested: activesupport ~> 4.1.11.Always verify the validity and compatibility of suggestions with your codebase. | Known moderate severity security vulnerability detected in activesupport < 4.1.11 defined in watir.gemspec. | watir.gemspec update suggested: activesupport ~> 4.1.11. | Always verify the validity and compatibility of suggestions with your codebase.
Known moderate severity security vulnerability detected in activesupport < 4.1.11 defined in watir.gemspec.
watir.gemspec update suggested: activesupport ~> 4.1.11.
Always verify the validity and compatibility of suggestions with your codebase.

**Comment by titusfortner** [comment]
Our gemspec has: 
```ruby
s.add_development_dependency 'activesupport', '~> 4.0', '>= 4.1.11'
```
Because I didn't want to limit people to only using 4.x which is what `~> 4.1.11` will do. The second argument will still ensure that no one uses a vulnerable version, regardless of what Github is complaining about.
(http://guides.rubygems.org/specification-reference/#add_development_dependencygem-requirements)
I suppose we could change it to `~> 4.1` to be more clear, but it won't make practical difference, and it is only a development dependency.
