### ISSUE TITLE
Default Timeout is not working for table() method

### ISSUE THREAD

**Issue by Rajagopalan-M** [watir/watir#710]
When I write the following code, 

`b.table(id: 'somethig').rows[1].click`
or
`b.table(xpath: ".//*[@id='lblSlip']/t/table").click`

`default timeout` to locate the element is not taken into account here, it immediately throws the following error

> Uncaught exception: unable to locate element: #<Watir::Table: located: false; {:xpath=>".//*[@id='lblSlip']/t/table", :tag_name=>"table"}>
> 	C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.10.3/lib/watir/elements/element.rb:583:in `assert_element_found'
> 	C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.10.3/lib/watir/elements/element.rb:578:in `assert_exists'
> 	C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.10.3/lib/watir/elements/element.rb:603:in `ensure_context'
> 	C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.10.3/lib/watir/element_collection.rb:124:in `elements'
> 	C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.10.3/lib/watir/element_collection.rb:70:in `to_a'
> 	C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.10.3/lib/watir/elements/row.rb:14:in `to_a'
> 	C:/Ruby24/lib/ruby/gems/2.4.0/gems/watir-6.10.3/lib/watir/element_collection.rb:48:in `[]'
> 	C:/Users/rajagopalan.m/RubymineProjects/Rajagopalan/SalaryAndTax/Tax_Slip.rb:17:in `<top (required)>'
> 
>

**Comment by titusfortner** [comment]
The second example works fine.

The first example isn't working because the first step of the `#elements` method is to call `#ensure_context` when it probably needs to be `#wait_for_exist` or `#wait_for_present`.

This code will work in the meantime:
`b.table(id: 'somethig').wait_until(&:present).rows[1].click`

**Comment by Rajagopalan-M** [comment]
@titusfortner 

@jkotests 

I have actually written the second one, first one I gave it for an example. It doesn't work in both ways. But expected output from WATIR is, it has to wait for both,right? If so, it must be a bug,right?

`b.table(id: 'somethig').wait_until(&:present).rows[1].click`

yes I am aware of this alternative but we need to give implicit wait for any function call like `b.link`, `b.element`, ` b.button`, `b.table` ,eh?

**Comment by titusfortner** [comment]
This is the bug I see:
When taking action on an element defined from a collection that has a parent element, and the parent element isn't present, the code does not wait for it.

I think the fix is a one line change in the code, but I don't have time this month to write the tests around it and see what works. 

This code should wait just fine, so I'm not understanding what your problem is with it.
`b.table(xpath: ".//*[@id='lblSlip']/t/table").click`

**Comment by titusfortner** [comment]
@Rajagopalan-M can you see if the 6.11.0.beta1 release fixes this? http://watir.com/watir-6-11-beta1/

**Comment by Rajagopalan-M** [comment]
Sure

**Comment by Rajagopalan-M** [comment]
@titusfortner 

The problem is very tricky now. It is still not resolved. 

When I write 

`b.table(xpath: ".//*[@id='lblSlip']/t/table").click`

It wait for table to present but when I write 

`b.table(xpath: ".//*[@id='lblSlip']/t/table").rows[1].click`

It's not even waiting for table, it immediately throws the error. 

**I will tell you the reason,** 

when you execute `b.table(xpath: ".//*[@id='lblSlip']/t/table").click` find element is called from `element_call` but when you execute `b.table(xpath: ".//*[@id='lblSlip']/t/table").rows[1].click` find_element is called even before `element_call` of click method.

**Comment by Rajagopalan-M** [comment]
@titusfortner 

May I know did you notice the above comment?

**Comment by titusfortner** [comment]
The issue here is with any action on an element obtained from a collection. The `#[]` method does the locating, rather than lazy loading. We want it to wait for an action, but not wait for a predicate. Elements we can completely lazy load, so element_call works. Lazy loading would be tricky for collections since we've opened this up the class to handle mixed classes. So we can't just throw in an index value. Especially when we need to deal with input classes as well.

I think it's doable, and important, but it won't be trivial.

**Comment by Rajagopalan-M** [comment]
@titusfortner Okay, thank you. Willing to check this once the next release is done.
