### ISSUE TITLE
Watir 6.11 collections no longer compatible with enumerable.

### ISSUE THREAD

**Issue by Donavan** [watir/watir#738]
In commit 7c4e28861b1c12a69b2527f8a567046b5fcdf56e, the implementation of [] for element collection was changed in a way that breaks compatibility with enumerable.

[] has to accept more than just a single index.  By removing the to_a[idx] you've removed the ability to use ranges and force us to take one at a time.  For example: divs[1..4] should work and did work in 6.10

**Comment by titusfortner** [comment]
Technically, this has nothing to do with Enumerable, since that module is intended to provide a means for iterating, and only requires the implementation of an `#each` method. Additionally, the current documentation specifies that the `#[]` method only supports an `Integer`
>     # @param [Integer] idx Index of wanted element, 0-indexed

With the current code, you can use: `divs.to_a[1..4]`

That being said, adding explicit support for a Range input makes sense to me, so I made the PR referenced above.
