### ISSUE TITLE
lot of warn messages with latest watir for text assertions

### ISSUE THREAD

**Issue by matamehta** [watir/watir#751]
## Meta -
Watir Version: 6.11.0
Selenium Version: selenium-webdriver (3.12.0)
Browser Version: Chrome Version 67.0.3396.87 (Official Build) (64-bit)
Browser Driver Version: ChromeDriver 2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8)
OS Version: Mac

## Expected Behavior - 
recently updated to latest watir and selenium from 6.5.2 and 3.5.2 and text variations  like `tr[0].text == /Application/`, or `tr[0].text == "Application"` or
 `tr[0].text.include? "8(a) Initial Application"`
worked normally with old versions of watir and selenium

**Comment by jkotests** [comment]
@matamehta, can you provide the HTML and Watir code that you are running?

Note that the deprecation warning occurs when locating the elements. It's not related to how you inspect the text and use it in a comparison. In other words it would be related to a code like `browser.tr(text: 'some text')`.

**Comment by titusfortner** [comment]
@jkotests your improvements on when to throw that exception didn't go out with 6.11, so I should release 6.12 sooner so that there are fewer of these calls.

As for this issue. If you are still getting the warnings in the next release, then you'll need to figure out how to fix your code to avoid breaking changes in future releases.
