### ISSUE TITLE
Iterating a collection fails if elements are removed during iteration

### ISSUE THREAD

**Issue by abotalov** [watir/watir#769]
I use Nerodia but Watir has the same issue

## Expected Behavior -
If an element is removed during iteration, iteration fails.
I think if some element turns out to be stale, iteration should start from the beginning.

## Actual Behavior -
If some element is removed during iteration, an exception is raised.

## Steps to reproduce -
```
import nerodia

nerodia.default_timeout = 3
br = nerodia.browser.Browser()
br.goto("https://fiddle.jshell.net/SMZNH/177/show")
iframe = br.iframe()
for i in xrange(0, 100):
  iframe.button(text="add elements!").click()
  iframe.button(text="remove elements!").click()
  print len(iframe.elements(tag_name="p"))
```
fails with `UnknownObjectException: timed out after 3 seconds, waiting for #<HTMLElement: located: False; {'tag_name': 'iframe'} --> {'index': 0, 'tag_name': 'p'}> to be located`. In this situation I would expect Watir to start from the beginning, see that there are no elements anymore, and return 0.

**Comment by titusfortner** [comment]
So... this is a race condition. Watir is clicking the remove elements, then getting the list of elements before the javascript removes them. Our current implementation for locating an element collection checks the tag name of the element if it is not specified. Since this element is now stale, Watir is dutifully continuing to attempt to locate it and failing.

So, the first thing is that if you were to specify `iframe.ps.size` it would not throw an exception because it wouldn't be making the `#tag_name` call. 

When I add in the ability to use the provided tag_name instead of making that call, though, I get:
```
6
0
6
6
6
6
6
6
0
6
```
Which isn't what you want because of the race condition. So you'll still need something like this before the print statement to make it work:
```
iframe.p.wait_while_present
```

**Comment by abotalov** [comment]
Ok, actually I see that I was mistaken when saying that iteration should start from beginning. If user code performs side-effect actions like clicks, reperforming them would be bad...
