### ISSUE TITLE
Proxies with authentication do not work

### ISSUE THREAD

**Issue by limsammy** [watir/watir#798]
## Meta -
Watir Version: 6.14

## Expected Behavior - Following the proxy guide it should work. Here is how I'm structuring my proxy hash: 
```
proxy = {
      http: 'http://user:pass@35.197.175.20:3128',
      ssl:  'https://user:pass@35.197.175.20:3128'
    }
```
I then build my browser like this: `browser = Watir::Browser.new :chrome, headless: true, proxy: proxy`

## Steps to reproduce -
```
proxy = {
      http: 'http://jaicooker:proxypass@35.197.175.20:3128',
      ssl:  'https://jaicooker:proxypass@35.197.175.20:3128'
    }

    browser = Watir::Browser.new :chrome, headless: true, proxy: proxy
    browser.goto("http://www.whatsmyip.org/")
    ip = browser.span(:id, "ip").text

    puts "IP: #{ip}"
```

**Comment by ranle** [comment]
any news on that?

**Comment by titusfortner** [comment]
There are a number of capabilities bugs reported. The way I implemented `Watir::Capabilities` in the first place is flawed and I'm in the process of redoing it. In the process of redoing it, I've realized I don't like how `Selenium::WebDriver::Remote Capabilities` is implemented, so I'm flying out to meet up with @twalpole so we can hack on some code this weekend.  

For this specific issue, I'm not a proxy person. In the short term, I would try using Selenium classes to see if it works directly. If so my current work will fix the API and make the following moot. If it doesn't work, then there are deeper issues we'll need to investigate. 
Use [Selenium::WebDriver::Proxy](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/common/proxy.rb)
and pass it in to a Capabilities class:
`Selenium::WebDriver::Remote::Capabilities.chrome(proxy: proxy_instance)`
You can check the logs to make sure it is passing the values correctly:
`Selenium::WebDriver.logger.level = :info`

**Comment by jpwynn** [comment]
This would significantly increase the potential uses for Watir, if fixed. LMK if you need an early tester.

Tried the same thing as linsammy, with and without the 'http' as per this note from someone who tested a number of proxy issues (although did not try authentication, it seems)

https://github.com/ttilberg/using-proxy-with-watir

**Comment by titusfortner** [comment]
@jpwynn the question is whether it works in Selenium. Watir is essentially just wrapping the Selenium code for it at this point.

If the Selenium code does work, but it isn't working in Watir, then I'll need to finish fixing Capabilities implementation.

If the Selenium code does not work, then we need to figure out if it is the Selenium code or the driver support, and raise the issue in the correct place.

**Comment by k5o** [comment]
@titusfortner I'm not sure if any extra work had been done on this end, but my findings so far are that if I do something like:

```
proxy = Selenium::WebDriver::Proxy.new(
  http: 'username:password@myproxy.com:port',
  ssl:  'username:password@myproxy.com:port'
)

browser = Watir::Browser.new(:chrome, proxy: proxy)
```

That, despite the proxy being properly added to the browser instance (as evidenced by `:info` level logging), the browser will navigate without using the proxy (which is the same problem as the OP)

However, if I do this instead (not passing in username/password to the proxy):

```
proxy = Selenium::WebDriver::Proxy.new(
  http: 'myproxy.com:port',
  ssl:  'myproxy.com:port'
)

browser = Watir::Browser.new(:chrome, proxy: proxy)
```

When navigating to a page, it will correctly prompt me for a username and password in order to connect to the proxy. When I input the credentials manually, the proxy seems to be applied properly and I can verify that using the steps in the OP. 

The problem, however, is that I don't know if there's a way to programatically tell Watir to input my username and password into this alert box. My console appears to hang after I input commands as long as this alert is present, so if I type `browser.alert.exists?` (or literally any other browser method call), I'll get:

```
> browser.alert.exists?
2019-05-03 14:00:56 INFO Selenium -> GET session/2461c50199f1136b78a7efb6a0b515a3/alert_text
```

And the terminal hangs at that point (no input allowed) until I cancel out of the proxy authentication alert manually. So the behavior here is a bit strange as the expected way to authenticate doesn't work (as OP insisted), but also that while proxies work, there doesn't appear (to me) any way to authenticate them programatically without human input, which would make authentication an impossibility if run headless as far as I can tell. Hopefully I'm missing something, looking forward to hearing your thoughts, thanks.

**Comment by titusfortner** [comment]
Still not a proxy person, does setting these values work?
https://github.com/SeleniumHQ/selenium/blob/master/rb/spec/unit/selenium/webdriver/proxy_spec.rb#L32-L33

I'm pretty sure this is an issue that belongs in Selenium tracker and not Watir tracker, though.

**Comment by k5o** [comment]
It doesn't for me, it still prompts for a username/password for the proxy despite passing those keys/values. 

> I'm pretty sure this is an issue that belongs in Selenium tracker and not Watir tracker, though.

I figured but I thought since this was a relatively recent discussion that I'd add my two cents and maybe I was just missing something related to watir's handling of the proxy authentication dialog box :) Thanks for the help.

**Comment by titusfortner** [comment]
Yeah, this is going to be a selenium issue, then. Can you open an issue there?

**Comment by vnazarenko** [comment]
Any news on this?

**Comment by kanzaliwaj** [comment]
Watir: 6.16.5
I'm working behind a proxy

when i use this 
proxy = Selenium::WebDriver::Proxy.new(
  http: 'username:password@myproxy.com:port',
  ssl:  'username:password@myproxy.com:port'
)
browser = Watir::Browser.new(:chrome, proxy: proxy)

It does not work for me....
Anyone can give me help please ?

**Comment by mark0203** [comment]
Not sure if this helps for a local browser and with username+pwd, but what
happens if you do something like this?

ENV['HTTP_PROXY'] = 'http://192.168.1.10:3128'


Op do 21 nov. 2019 13:08 schreef kanzaliwaj <notifications@github.com>:

**Comment by dmigous** [comment]
stuck on this too

**Comment by titusfortner** [comment]
Closing since this is a Selenium issue.
