### ISSUE TITLE
obsured? method is not waiting for element to be present before it performs it's check

### ISSUE THREAD

**Issue by Rajagopalan-M** [watir/watir#818]
I have written this code in my project

> '' while @b.link(loc.first => loc.last).obscured?

This line immediately fails before element to be present but it's reporting the error by saying that it has waited for 30 seconds in **FIREFOX**

**Error**
Watir::Exception::UnknownObjectException: element located, but timed out after 30 seconds, waiting for #<Watir::Anchor: located: true; {:xpath=>"//a[text()=\"Workers' Compensation\"]/../../following-sibling::tr[2]/td/a", :tag_name=>"a"}> to be present

  0) AGCSquoteCreation Test1
     ?[31mFailure/Error: raise unknown_exception, msg?[0m
     ?[31m?[0m
     ?[31mWatir::Exception::UnknownObjectException:?[0m
     ?[31m  element located, but timed out after 60 seconds, waiting for #<Watir::Anchor: located: true; {:xpath=>"//a[text()=\"Workers' Compensation\"]/../../following-sibling::tr[2]/td/a", :tag_name=>"a"}> to be present?[0m
     ?[36m# ./Source/FrameWorkModules/Elements/Button.rb:50:in `clickLink'?[0m
     ?[36m# ./Source/FrameWorkModules/Browser/Framework.rb:12:in `block in execute'?[0m

**Comment by jkotests** [comment]
It's intentional that `#obscured?` does not wait for the element to be present - see https://github.com/watir/watir/pull/804#issuecomment-429669241

You highlighted Firefox. Does that mean you only have the problem in Firefox? It doesn't occur in other browsers?

**Comment by Rajagopalan-M** [comment]
Yes it's not happening in chrome.

**Comment by jkotests** [comment]
It'd help if you can isolate the markup needed to reproduce the problem.

**Comment by jkotests** [comment]
As an aside, if the element remains obscured, won't that loop run forever? Might be safer to do:

~~~~~~~~
@b.link(loc.first => loc.last).wait_until(&:present?).wait_while(&:obscured?).click
~~~~~~~~

**Comment by Rajagopalan-M** [comment]
This seems to be good idea and I am actually expecting something like this.
But here wait_until and wait_whike only waits for 30 sec , can I set my own
time?

**Comment by Rajagopalan-M** [comment]
@jkotests 

Hi, no, this solution is not working for me. It throws the same error

I have written this line

    @b.link(loc.first => loc.last).wait_until(&:present?).wait_while(&:obscured?).click

Note: this happens only in Firefox not in Chrome.

Watir::Exception::UnknownObjectException: element located, but timed out after 60 seconds, waiting for #<Watir::Anchor: located: true; {:xpath=>"//a[text()=\"Workers' Compensation\"]/../../following-sibling::tr[2]/td/a", :tag_name=>"a"}> to be present

  0) AGCSquoteCreation Test1
     ?[31mFailure/Error: raise unknown_exception, msg?[0m
     ?[31m?[0m
     ?[31mWatir::Exception::UnknownObjectException:?[0m
     ?[31m  element located, but timed out after 60 seconds, waiting for #<Watir::Anchor: located: true; {:xpath=>"//a[text()=\"Workers' Compensation\"]/../../following-sibling::tr[2]/td/a", :tag_name=>"a"}> to be present?[0m
     ?[36m# ./Source/FrameWorkModules/Elements/Button.rb:45:in `clickLink'?[0m
     ?[36m# ./Source/FrameWorkModules/Browser/Framework.rb:12:in `block in execute'?[0m
     ?[36m# ./Source/FrameWorkModules/Browser/Framework.rb:11:in `each'?[0m

**Comment by jkotests** [comment]
You can set your own time by passing in the timeout parameter:

~~~~~~~~
browser.element.wait_until(timeout: 5, &:present?)
~~~~~~~~

There was a chance that `#obscured?` wouldn't be a perfect approximation. We'll need the markup/CSS to help address the problem. Though if the exception is waiting for the element to be present, that sounds like a problem with `wait_until(&:present?)` rather than `wait_while(&:obscured?)`.

**Comment by Rajagopalan-M** [comment]
Actually its not working. It is not even waiting it immediately throws the
error .

**Comment by Rajagopalan-M** [comment]
@jkotests 

Actually now I have noticed that normal `click` method is not even waiting for element to present. That's why `wait_until(&:present?)` is not working I think.

**Comment by Rajagopalan-M** [comment]
@jkotests  Hi, I noticed that it works(waiting for element to be visible) for other sites. But it's not waiting for the site I am automating,it immediately throws the error. What might be the reason?

**Comment by jkotests** [comment]
@Rajagopalan-M , can you verify if the problem is either (1) lack of waiting or (2) incorrect determination for `#present?`?

For example, what do you get when doing a `@b.link(loc.first => loc.last).present?`? It sounds like Firefox thinks the element is displayed. Given it works in Chrome, it could be a bug in Firefox.

**Comment by kapoorlakshya** [comment]
Hey @jkotests, I am able to reproduce this in Internet Explorer 11 as well. Here is a quick test:

```
b = Watir::Browser.new :ie
b.goto 'http://watir.com'

b.div(class: 'intro').present? #=> true

b.div(class: 'intro').obscured? # raises Watir::Exception::UnknownObjectException
```

It returns `false` in Chrome.

**Comment by titusfortner** [comment]
Can you run this with `Selenium::WebDriver.logger.level = :debug` and get me the output?

**Comment by kapoorlakshya** [comment]
Yes, here it is for IE - https://gist.github.com/kapoorlakshya/f622b9be8395678b2b80196a3119f78d

**Comment by titusfortner** [comment]
Hmm, it looks like it is ending up in the loop for ElementNotFound, which is why it is checking for an iframe. Can you run it again also adding `Watir.logger.level = :debug`? Thanks!

**Comment by jkotests** [comment]
I think the problem is in `Element#scroll_into_view`, which is called by `#obscured?`.

~~~~~~~~
b.div(class: 'intro').scroll_into_view
#-> C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.15.0/lib/watir/elements/element.rb:739:in `raise_present': element located, but timed out after 30 seconds, waiting for #<Watir::Div: located: true; {:class=>"intro", :tag_name=>"div"}> to be present (Watir::Exception::UnknownObjectException)
#-> 	from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.15.0/lib/watir/elements/element.rb:791:in `rescue in element_call'
#-> 	from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.15.0/lib/watir/elements/element.rb:802:in `element_call'
#-> 	from C:/Ruby23/lib/ruby/gems/2.3.0/gems/watir-6.15.0/lib/watir/elements/element.rb:352:in `scroll_into_view'
#-> 	from webdrivers.rb:11:in `<main>'
~~~~~~~~

**Comment by kapoorlakshya** [comment]
Watir debug log by itself - https://gist.github.com/kapoorlakshya/6d006f78c10966e7a5055daaf9c0acc5

Selenium + Watir - https://gist.github.com/kapoorlakshya/237ed3d00e7b2f32a769b0449aa0325b

@jkotests I have had problems with that method before. Don't remember the exact exception, but just in case this helps, I ended up using `browser.execute_script('arguments[0].scrollIntoView();', el)` instead.

**Comment by jkotests** [comment]
IE and Firefox do not like scrolling to the `div` - both raise the `Selenium::WebDriver::Error::ElementNotInteractableError`. Message says that the element is not reachable by keyboard. Seems like a weird expectation.

We seem to have 2 problems:
1. `#scroll_into_view` does not have specify a precondition for `#element_call`. As result, there is no retry.
2. Some drivers do not like scrolling to non-keyboard focusable elements.

**Comment by titusfortner** [comment]
@p0deje what do you think of pulling `watir-scroll` code directly into Watir? I was going to ask about doing this for Watir 7, but no reason not to do it ahead of time. It is technically currently a Monkey Patch since it puts additional methods on Watir objects rather than composing new objects. Unlike WatirAngular, etc, this code is universally applicable to users, and there isn't an alternative implementation that this will prevent people from using. Plus the code seems super stable at this point. We discussed at TPAC adding this functionality to w3c specification directly in future versions, so Watir will eventually be implementing it with Selenium calls regardless.

It would be useful right now because we can avoid using `#scroll_into_view` here.

**Comment by Rajagopalan-M** [comment]
Oh great, problem is diagnosed now

**Comment by p0deje** [comment]
@titusfortner Some of APIs watir-scroll uses are not part of any standard (e.g. `window.scrollTo`), but quick search shows that all of them are supported by major browsers, so I have nothing against pulling it into Watir codebase. Let's only keep its API the same.

**Comment by Rajagopalan-M** [comment]
@jkotests 

Can you please help me here 

https://github.com/SeleniumHQ/selenium/issues/7917
