### ISSUE TITLE
When checking for staleness deprecation warning is raised by checking for the presence of a stale element, the element will always be declared not present.

### ISSUE THREAD

**Issue by Castone22** [watir/watir#852]
## Meta -
Watir Version: 6.16.5
Selenium Version: 3.141.0
Browser Version: 71.0.3578.98
Browser Driver Version: 2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90)
OS Version: Windows 10.0.16299 Build 16299

## Expected Behavior -
I have an element on the page that becomes stale due to other elements being added and removed from the dom causing it to move itself, I expect that when i ask if it was present, It should be found without me having to manually relocate it.  (If you want an example, i'll need time to build one in fiddle or something)
## Actual Behavior -
The element is stated as not found unless we recheck it.

Looking through how the deprecation is raised, i was able to figure out *why* this happens.
```ruby
    def present?
      displayed = display_check
      if displayed.nil? && display_check
        Watir.logger.deprecate 'Checking `#present? == false` to determine a stale element',
                               '`#stale? == true`',
                               reference: 'http://watir.com/staleness-changes',
                               ids: [:stale_present]
      end
      displayed
    rescue UnknownObjectException, UnknownFrameException
      false
    end
```

In this block the display check in `if displayed.nil? && display_check` is not presisted back to displayed, so it returns the first result, even after relocating after the reset!.

Defining
```ruby
    def present?
      displayed = display_check
      if displayed.nil? && (displayed = display_check)
        Watir.logger.deprecate 'Checking `#present? == false` to determine a stale element',
                               '`#stale? == true`',
                               reference: 'http://watir.com/staleness-changes',
                               ids: [:stale_present]
      end
      displayed
    rescue UnknownObjectException, UnknownFrameException
      false
    end
```
seems to fix it.

**Comment by titusfortner** [comment]
Yes, this is intentional. Returning the original value is the backward compatible behavior. What is in the conditional block is essentially checking to see if the code in use is going to give a different result in Watir 7, in which case the user needs to update their code.

We test this by expecting the warning to be thrown only under the condition we expect: https://github.com/watir/watir/blob/master/spec/watirspec/elements/element_spec.rb#L361
If it were throwing the warning in cases we did not expect, the test runs would include a bunch of deprecation warnings that do not exist: https://travis-ci.org/watir/watir/jobs/478454267

As to your use case:
> I have an element on the page that becomes stale due to other elements being added and removed from the dom causing it to move itself, I expect that when i ask if it was present, It should be found without me having to manually relocate it.

I might be missing something, asking `#present?` on a stale element should return `false` right now, not relocate it. Taking an element that is stale will automatically relocate it.

The change in Watir 7 is that `Element#present?` means "is there an element that exist that matches all of the locators I've provided?" It answers that question regardless of whether the DOM has changed. If you want to know if the object that has been cached is invalid, you need to call `#stale?` instead. More thorough explanation is here: http://watir.com/staleness-changes/

Let me know if there's something I can make more clear in the write-up.

**Comment by titusfortner** [comment]
Also of note, the final version of Watir 6.x will have all of the deprecation warnings updated, hopefully in a way that is entirely accurate in which of the current specs will pass or fail in Watir 7.

**Comment by Castone22** [comment]
I'm trying to think of a time i'd actually want to know an element was stale, and i'm coming up with a blank short of testing some weird angular voodoo.  Maybe i'm misunderstanding the intent of this change, though I know in watir 6.6, checking the kind of element i described would cause watir to return that it was present.  In current versions, it very much does not short of us manually having to tell watir to relocate the element each time before we make a check against an elements presence.

**Comment by titusfortner** [comment]
Agreed, theoretically you should never need to know if an element went stale, which is why the current behavior doesn't really make sense, because it treats staleness as a lack of presence, when they shold be separate concepts.

Ok, if there was a breaking change I want to know about it. It might be what was reported in #851 which was a use case that did break backward compatibility, but I didn't foresee that and would expect it to be rare.

Can you show me code? I'm not sure I understand what you mean by:
> manually having to tell watir to relocate

Also, why do you need to check the presence of the element? If you are doing something with it, presence is dealt with automatically.

**Comment by Castone22** [comment]
I don't really have an example offhand, but the general gist of the design is we have a test framework that crawls around our application, tries filling in various forms, then checks if fields appeared or disappeared based on what was filled in.

**Comment by titusfortner** [comment]
If you are looking to see if a previously located element disappeared, then you want to use`!my_element.stale?`. Actually, that's probably not a bad method name to create and be the opposite of stale.

**Comment by titusfortner** [comment]
```
<div>one</div>
<div>two</div>
<div>three</div>
```
```
second_div = browser.div(index: 1)
second_div.text # => "two"
second_div.stale? # => false
second_div.present? # => true

disappear_second_element

second_div.stale? # => true
second_div.present? # => true
second_div.stale? # => false
second_div.text # => "three"

**Comment by Castone22** [comment]
We're not checking that it disappeared though, we're checking that it stayed after the dom update... which makes doing `!#.stale? && #.present?` feel really clunkly.  This essentially means you'd have to do this as a check for any element that you're testing against on a single page application of any kind just to ensure you actually safely find the element if i'm understanding this correctly.  One of the things i've liked about watir after dealing with other wrappers is the fact that I don't need to care if the element went stale.

If you've got time at some point, we can move this into slack or something as github isn't exactly the greatest forum for this kind of discussion.

**Comment by Rajagopalan-M** [comment]
That's the same thing I like in WATIR. The way watir takes care of Stale
Element is amazing.

**Comment by Castone22** [comment]
Okay, i was doing some digging, and i got to the bottom of what seems to cause this.

It looks like it's got something to do with how a given single page app is handling its data binds (looks like this one's guidewire.)  The page does a sort of... soft refresh each time you enter data into a field which causes a lot of elements on the page to go stale because it's a new dom each refresh.  I'm trying to think if there's a good way to replicate that in codepen....

**Comment by titusfortner** [comment]
You shouldn't need to make both stale and present calls, I was just showing what would cause the value to change.

I'm really confused about your use case at this point. If you are just using the element, you never have to worry about it. The only change is if you want to ask the driver if the object it previously cached is still valid, you used to be able to do that with present, and now you need to do it with stale.

Whether here or in slack, I just need a reproducible case that explains your frustration.

**Comment by Castone22** [comment]
Yeah, i'm trying to figure out how to reproduce the behavior i'm seeing, looks like Angular, Ember and all the other SPAs data-bindings don't work the same way as whatever the heck guidewire's doing.  Given it's an internal guidewire app and i can't just spin one up and show you what's going on, I'm at a bit of a loss here.

**Comment by jkotests** [comment]
@Castone22 , even if we cannot run your test case, the following would give us a better idea of what might be wrong:
* Can you share the Watir code that you are running.
* Can you share the webdriver logs that it generates - add `Selenium::WebDriver.logger.level = :info` before the section of coding having issues.

**Comment by Castone22** [comment]
Code: https://gist.github.com/Castone22/f6da29e54d4b70d5d29da509e1233619


The framework is open source so i can share code regarding it.
it can be found at https://github.com/OzFramework/oz

Validation engine is basically a wrapper that catches exceptions and stores them while the page is scanned, then blows up when validation_mode is exited.
Data Engine is a tool that handles pulling data from various sources such as yaml.

The test looks like
1. The Page Loads, and we store information in our internal element wrapper that contains a the selectors and the element type, we do not create watir elements yet
1. Each element is filled out with data retrieved from the data engine.  At this point each watir element was created as we called `#.watir_element.set` on each element.  At this point the elements have been cached.
1. Seemingly Guidewire's application triggers a DOM update at this point.
1. Without recreating the page, we now iterate over all elements that were filled in, first checking that they were present, then checking that they contain the information we put in.
    - The reason for this is that the program makes fields appear and disappear based on the contents of others
1. The logs show that the test for presence fails, however the test for the text they contain succeeds.
    - curiously, any further interactions will succeed at this point, because watir DID relocate the element when we checked presence, it just didn't persist the fact that it did, this is also why it finds that there was text in the field despite not actually finding the field itself.

logspew can also be found in the gist.

**Comment by Castone22** [comment]
It's worth noting, the more i look into this, the more i'm starting to think it's guidewire weirdness and we'll (my team) just need to write special logic to handle what it does.

**Comment by jkotests** [comment]
I think the basic principle is:

~~~~~~~~
browser = Watir::Browser.new
browser.goto 'http://a.testaddressbook.com/sign_in'
field = browser.text_field(data_test: 'password')
field.set('password')
browser.refresh
p field.present?
~~~~~~~~

Which currently (6.16.5) gives:

~~~~~~~~
#=> 2019-01-28 14:48:26 WARN Watir [DEPRECATION] ["stale_present"] Checking `#present? == false` to determine a stale element is deprecated. Use `#stale? == true` instead; see explanation for this deprecation: http://watir.com/staleness-changes.
#=> nil
~~~~~~~~

In contrast, 6.6 gave:

~~~~~~~~
#=> true
~~~~~~~~

**Comment by Castone22** [comment]
I tried running the same test in 6.8.4 and it appears to work, looks like the changing commit was https://github.com/watir/watir/commit/ca377c3d0041edae59bd8ce7bb7390571ac4a471?diff=split#diff-a0982f69261cbd95246962ebecdabf3cL569

Which explains a lot.  Before there was a safety check in place to ensure that the element couldn't be stale by checking if it was stale (which is slow so it was removed judging from the comment).

And yes, i think that's correct, judging by this.

**Comment by titusfortner** [comment]
Wait, present? Is returning nil? Is the backward compatibility I'm trying to maintain, not the behavior in earlier 6.x versions? I think I'm being so careful and yet I can't always keep track...

**Comment by jkotests** [comment]
@titusfortner , correct, we are currently returning nil. We've apparently gone through different values in 6.x (true, false and nil):

~~~~~~~~
Version     Result
6.16.5      nil
6.15        nil
6.14        nil
6.13        false
6.12        false
6.11        false
6.10        true
6.9         true
6.8         true
6.7         true
6.6         true
...
6.0         true
5.0         true
~~~~~~~~

**Comment by titusfortner** [comment]
Sigh. That's not good. How did I screw up our tests so they didn't catch this? I'm at a company retreat this week. I'll see if I can find time to fix this, thanks for bringing it to my attention.

**Comment by kapoorlakshya** [comment]
@jkotests In reference to your table, `#stale?` and `#present?` are returning a different value for me in version 6.15.1 compared to 6.14 and 6.16.5.

I am using the `page-object`  (2.2.5) gem, and here is how I am testing this:

**Element**
```ruby
[1] pry(#<Object>)> poe.inspect
=> "#<PageObject::Elements::SelectList:0x0000001580e4d0 @element=#<Watir::Select: located: true; {:id=>/^ctl00_ctl00_BC_MC_MainTS_(.+)_ViewOptions$/, :tag_name=>\"select\"}>, @platform=#<PageObject::Platforms::Watir::PageObject:0x0000001580e4a8 @browser=#<Watir:
:Select: located: true; {:id=>/^ctl00_ctl00_BC_MC_MainTS_(.+)_ViewOptions$/, :tag_name=>\"select\"}>>>"
```
**Steps**
```ruby
poe.option(text: 'Dependent - Standard View').select
@current_page.wait_for_postback # Partial refresh

# debugger breakpoint

poe.text
```

**6.14**
```ruby
[1] pry(#<Object>)> poe.stale?
=> true
[2] pry(#<Object>)> poe.present?
2019-02-06 14:21:21 WARN Watir [DEPRECATION] ["stale_present"] Checking `#present? == false` to determine a stale element is deprecated. Use `#stale? == true` instead; see explanation for this deprecation: http://watir.com/staleness-changes.
=> nil
[3] pry(#<Object>)> poe.text
=> "Dependent - Standard View"
[4] pry(#<Object>)> poe.reset!
=> nil
[5] pry(#<Object>)> poe.present?
=> true
```

**6.15.1**
```ruby
[1] pry(#<Object>)> poe.stale?
=> false
[2] pry(#<Object>)> poe.present?
=> true
[3] pry(#<Object>)> poe.text
=> "Dependent - Standard View"
[4] pry(#<Object>)> poe.reset!
=> nil
[5] pry(#<Object>)> poe.present?
=> true
```

**6.16.5**
```ruby
[1] pry(#<Object>)> poe.stale?
=> true
[2] pry(#<Object>)> poe.present?
2019-02-06 15:08:29 WARN Watir [DEPRECATION] ["stale_present"] Checking `#present? == false` to determine a stale element is deprecated. Use `#stale? == true` instead; see explanation for this deprecation: http://watir.com/staleness-changes.
=> nil
[3] pry(#<Object>)> poe.text
=> "Dependent - Standard View"
[4] pry(#<Object>)> poe.reset!
=> nil
[5] pry(#<Object>)> poe.present?
=> true
```

Seems to me that 6.15.1 is returning the desired result for `#present?`.

Also, when I run this without the breakpoint on IE 11 and Chrome 72, the drivers behave differently (with 6.16.5). Here's how IEDriver and ChromeDriver respond when `poe.text` is invoked after the page refresh:

**IEDriver**

```ruby
2019-02-06 16:35:13 WARN Watir [DEPRECATION] ["stale_exists"] Checking `#exists? == false` to determine a stale element is deprecated. Use `#stale? == true` instead; see explanation for this deprecation: http://watir.com/staleness-changes.
	Invalid internal element ID requested: 3a93f208-7328-40a5-bdf6-018cc30d443f (Selenium::WebDriver::Error::NoSuchElementError)
```

**ChromeDriver**

```ruby
2019-02-06 16:06:30 WARN Watir [DEPRECATION] ["stale_exists"] Checking `#exists? == false` to determine a stale element is deprecated. Use `#stale? == true` instead; see explanation for this deprecation: http://watir.com/staleness-changes.
	timed out after 30 seconds, waiting for true condition on #<Watir::Select: located: true; {:id=>/^ctl00_ctl00_BC_MC_MainTS_(.+)_ViewOptions$/, :tag_name=>"select"}> (Watir::Wait::TimeoutError)

```

Can you or someone else please perform a similar test on these three versions and share the results? This is really strange because 6.14 works fine, but 6.16.5 which behaves the same (`#exists?` and `#present?`) fails to retrieve the `#text`.

**Comment by jkotests** [comment]
@kapoorlakshya , the timeout you're seeing in `Select#text` seems to be a different issue so I split it to #853.  

As I mentioned on Slack, I wasn't able to reproduce the results for 6.15.1. Given that the select is included in the partial refresh, `poe.stale?` should have been returning `true`.

**Comment by kapoorlakshya** [comment]
@jkotests You are right! `stale?` should return `true` because the element is included in the refresh.

**Comment by titusfortner** [comment]
I now understand my confusion here. In 6.10 we have specs like:
"#visible? raises UnknownObjectException exception if the element is stale"
"#present? returns false if the element is stale"

Which isn't actually what they were testing. They were supposed to be testing how Watir was handling Selenium throwing staleness exceptions, not testing the final result after an element has gone stale.

Recall that in `watir-webdriver`, the default value was to not cache the element and always relocate. If `Watir#always_locate = false` was set, then it would never relocate. So the behavior was:

```
browser.refresh
expect(element.exists?).to be Watir.always_locate?
```

So we fixed that in Watir 6 to cache the element, and only relocate when we tried to re-use it and could not. We also decided that `#exist?` & `#present?` should do the smart thing and relocate when the cache went stale.

So, yes, I broke this behavior in 6.11. Then when releasing 6.12 [I complained about how this behavior was bad](http://watir.com/watir-6-12/#deprecations) instead of realizing that it was actually a bug I'd introduced in the previous version of Watir. I'm pretty sure I was reliving 2016 arguments in my head about how it should all work. Sigh

So, I get to remove the deprecations I added and straight up relocate for `#exist?` and `#present?` which is what has always made sense to do...

**Comment by titusfortner** [comment]
This should have been fixed by: https://github.com/watir/watir/commit/e036ffaa5d63e8c54c56c630ab7cba2f0bdce463
