### ISSUE TITLE
Is Watir still maintained?

### ISSUE THREAD

**Issue by mstroming** [watir/watir#882]
I'm trying to decide whether to use Watir or Capybara. Is Watir still maintained? I don't see any recent commits.

**Comment by Rajagopalan-M** [comment]
WATIR is still being maintained. I am using WATIR. See the recent questions in stack overflow. Start using WATIR you will have more support. Post your question in stack overflow by tagging WATIR.

**Comment by titusfortner** [comment]
Yes, but... I've been gatekeeping this project, but have been too busy to push things forward. I did a bunch of coding 6 months ago that I never finished/merged and have literally done 6 long overseas trips for work since then.

Not using watir on a daily basis has made it a little harder for me to prioritize it, and there is some Selenium development that really needs to be done before I/we can fix a number of issues in watir. I keep saying I'll dig into the code starting "next week." Hopefully with the holidays and work things slowing down finally I'll be able to make more progress.

Make your decision on Capybara/watir based on the approach you are looking to take. Capybara works better integrated with rails, I would argue that watir has a more simple API that relies less on conventions. But both projects will do what you need.
