### ISSUE TITLE
scroll_into_view on present element throws UnknownObjectException immediately

### ISSUE THREAD

**Issue by CrunchwrapSupreme** [watir/watir#884]
## Meta -
Watir Version: 6.16.5
Selenium Version: 3.141.0
Browser Version: Google Chrome 79.0.3945.88
Browser Driver Version: Chromedriver 79.0.3945.36
OS Version: Centos 7
Ruby Version: 2.5.5

## Expected Behavior -
```ruby
scroll_label = label_element(text: label)
wait_until(3, "Failed to find label #{label} to scroll into view") do
    scroll_label.present?
end

scroll_label.scroll_into_view
```

Should simply scroll to a given text label inside of a modal dialog.

## Actual Behavior -
Throws Watir::Exception::UnknownObjectException immediately when the scroll_into_view method is reached. Error message indicates a timeout of 30 seconds but this is incorrect as there was no wait time:
> element located, but timed out after 30 seconds, waiting for #<Watir::Label: located: true;{:text=>"Can Create Dashboards", :tag_name=>"label"}> to be present (Watir::Exception::UnknownObjectException)

I rolled back selenium-webdriver to 3.141.0 with recommendation from https://stackoverflow.com/questions/56445641/ruby-watir-selenium-webdriver-depricated-warning due to depreciation warnings after the upgrading to 16.5 but this did not rectify the issue (selenium was updated as well).

![Screen Shot 2020-01-02 at 2 13 30 PM](https://user-images.githubusercontent.com/30894202/71692588-ed0ea080-2d6f-11ea-91d0-d64295b7d28e.png)

**Comment by Rajagopalan-M** [comment]
Yes this is the same problem I am facing too. Yes I have upgraded to selenium as well . @jkotests  It throws this exception immediately but If I rescue the execution for few seconds, then watir handles this properly.

**Comment by jkotests** [comment]
Watir's error message is misleading. This isn't a waiting issue - even if the wait did wait for the full 30 seconds, `#scroll_into_view` will still not work.

The root of the problem is that Selenium's `#location_once_scrolled_into_view`, which is what Watir's `#scroll_into_view` is calling, does not work for non-interactable elements (in this case a label). Selenium is using `#send_keys` to bring the element into view, which only works for keyboard-interactable elements:
> The Element Send Keys command scrolls into view the form control element and then sends the provided keys to the element. In case the element is not keyboard-interactable, an element not interactable error is returned. - https://www.w3.org/TR/webdriver/#element-send-keys

I would suggest logging a bug in the Selenium project - ie I don't think it makes sense that their `#location_once_scrolled_into_view` does not work for label elements.

To workaround the problem, I would try using Watir's other scrolling method:

~~~~~~~~
scroll_label.scroll.to
~~~~~~~~

**Comment by titusfortner** [comment]
Thanks for this, we're going to go ahead and deprecate that method in favor of using the new scrolling methods:
https://github.com/watir/watir/commit/19755187fe4cdb2dc22b77e62e20bf439de16aa8

I was going to just change the implementation, but then the spec made me realize that it is providing a return value that we wouldn't have. So deprecation.
