### ISSUE TITLE
when using iframes, where should after_hooks execute?

### ISSUE THREAD

**Issue by MatthewMazaika** [watir/watir#889]
in the default context? or the current iframe?

in the example provided in #888, the after_hook was updated to be
```
      @page_after_hook = proc { @yield = browser.h1.text == 'Iframes' }
```

on that [sample page](https://github.com/watir/watir/blob/master/spec/watirspec/html/iframes.html) , there is an `<h1>Iframes</h1>`, but the element call that is triggering the `after_hook` is inside [this frame](https://github.com/watir/watir/blob/master/spec/watirspec/html/iframe_1.html) which also has `<h1>Frame 1</h1>`

after #888 is fixed, in the `after_hook`, would the evaluation of `browser.h1.text` pull back `Iframes` from the main page? or `Frame 1` from within the referenced iframe?

**Comment by MatthewMazaika** [comment]
we are upgrading from `watir-webdriver` and there it appears that when the `after_hook` fires (only after actions, not simply switching context into the frame), it will pull back the `Iframes` values from the main page

**Comment by titusfortner** [comment]
So, assuming the fix for 888 is to remove the after hook execution on frame switching...
This issue is about when a click or the like happens inside an iFrame, where the after hook code gets executed...

`browser` is always going to refer to the top level browsing context outside of frames, so if you need to evaluate the h1 inside a frame, you'll need to reference that inside the block:

```
      @page_after_hook = proc { @yield = browser.iframe(id: 'iframe_1').h1.text == 'Iframes' }
```

If I'm missing something else from this question, let me know...
