### ISSUE TITLE
Test cases execution

### ISSUE THREAD

**Issue by dariyaamruth** [watir/watir#895]
## Meta -
Watir Version: 6.15
Selenium Version: --
Browser Version: Chrome 79
Browser Driver Version:  
OS Version: Ubuntu 18.04

## Expected Behavior -
I am working on product which is having 10000 test cases and we have weekly release that leads to execute all test cases. By using Watir 6.15, Continues test cases execution is failing. How to execute all Test cases in one shot? or Can you suggest any method/process to follow for execution?

**Comment by jarmo** [comment]
Watir is just a browser automation tool and is not meant to be used like that. Use Watir with a test framework to achieve your requirements (for example [RSpec](https://rspec.info/)).

**Comment by titusfortner** [comment]
Yeah, this is good practice question best asked on Stack Overflow rather than a Github issue. Ideally you restart the browser in the before each hook of RSpec so that one failing test doesn't kill your other tests. This does slow down test execution, which is why I recommend speeding up overall test suite run times by executing tests in parallel with a Selenium Grid, or a service like Sauce Labs. (disclaimer: I work at Sauce Labs)
