### ISSUE TITLE
v6.19.0 doesn't work with selenium-webdriver 4

### ISSUE THREAD

**Issue by cameronheard** [watir/watir#921]
I may just be seeking clarification. Is the intention that 6.19.0 only works with selenium-webdriver  3.142.7? After the release of 6.18.0 which worked with selenium-webdriver 4, I didn't expect the next release to back down from that.

## Meta -
Watir Version: 6.19.0
Selenium Version: 4.0.0.beta2

## Expected Behavior -
These gems work together.
## Actual Behavior -
`watir` requires `selenium-webdriver` 3.142.7

**Comment by titusfortner** [comment]
Watir 6.x is not guaranteed to support Selenium 4 (or Ruby 3). 
6.19 is intended to support the way that Watir 7 will work with Selenium 4, so that you can update your code in Watir 6.19 with Selenium 3 in a way that will work in Watir 7 with Selenium 4.

All of that being said, what is the specific issue you are facing?

**Comment by cameronheard** [comment]
Thanks for the quick response. My issue was that 6.18 allowed me to experiment with selenium 4 beta and 6.19 doesn't, since the dependency in the gemspec now specifies selenium-webdriver = 3.142.7. That surprised me so I filed this ticket.

**Comment by titusfortner** [comment]
Oh, I see what you mean. Ok, yeah, that was an oversight. I hard coded it for running my tests and then didn't change it.

**Comment by titusfortner** [comment]
Fixed in 6.19.1
6df06192f384644c3c8acb6404a0cbfb28dbbc5f
