### ISSUE TITLE
Watir::Capabilities doesn't support camel case anymore, only supports snake case.

### ISSUE THREAD

**Issue by sandeep-mm** [watir/watir#954]
## Meta -
Watir Version: 7.1
Selenium Version: 4.1
Browser Version: Chrome 96.0.4664.93
Browser Driver Version: ChromeDriver 96.0.4664.45
OS Version: OSX Monterey

## Steps to reproduce -
Define browser options hash with camel case selenium capability and then try to instantiate a browser instance by passing these capabilities as `options:` as shown below:
```
require 'watir'

browser_options = {
  browserName: "Chrome",
  browserVersion: "96",
  acceptInsecureCerts: true
}

browser = Watir::Browser.new :chrome , options: browser_options, url: <grid_hub_url>

browser.quit
```
Watir throws following error for above:

```
/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-4.1.0/lib/selenium/webdriver/remote/response.rb:56:in `assert_ok': The property '#/alwaysMatch/goog:chromeOptions' contains additional properties ["browserName", "browserVersion", "acceptInsecureCerts"] outside of the schema when none are allowed in the payload. (Selenium::WebDriver::Error::WebDriverError)
```

**Comment by titusfortner** [comment]
Sorry I missed this issue. This is by design. Ruby projects should require snake cased symbols as keys for these things.

Selenium has had a lot of bugs and unintended consequences over the years by trying to support Strings, Symbols, Snake Case, Camel Case, and adding things via constructor, methods, and faking Hash syntax
